### ISSUE TITLE
Incremental formatting with a cache file

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#173]
Similar to the TypeScript compiler's `--incremental` flag, it might be neat to have a similar flag that only bothers formatting files that haven't been formatted since the last time it ran.

**Comment by bajtos** [comment]
> formatting files that haven't been formatted since the last time it ran.

Time-based detection may be unreliable, aren't some tools (`git`, `tar`) restoring `mtime` to values in the past? IMO, it's better to introduce a cache of files that are known to be well formatted. For example, we can use the relative path as the key and a hash of the configuration + the file content as the value.

In https://github.com/prettier/prettier/issues/5853, somebody suggested to use [xxHash](https://github.com/Cyan4973/xxHash) for its performance.

**Comment by dsherret** [comment]
@bajtos thanks for the heads up about that twox-hash algorithm. I'm using it to implement locally saved plugins in #242 and will use it here later.

**Comment by dsherret** [comment]
This is implemented now as either `dprint fmt --incremental` or specify `"incremental": true` in the configuration file.

It seems to take 0.1s in about every project I've tried.
