### ISSUE TITLE
Investigate running JS in WASM

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#207]
With the new Rust CLI running WASM plugins, I wonder how hard it would be to create a plugin that runs JS code. Perhaps deno_core (https://docs.rs/deno_core/0.45.0/deno_core) could be used here.

Edit 2020-06-03: Look into https://bellard.org/quickjs/

**Comment by bartlomieju** [comment]
@dsherret let me know if you need any help with integration

**Comment by dsherret** [comment]
@bartlomieju cool thanks! This is something for the future. It looks like I could just use rusty v8. The example in there seems simple enough... I’ll try to see if it compiles to wasm soon...  https://docs.rs/rusty_v8/0.4.2/rusty_v8/

**Comment by dsherret** [comment]
I was able to get quickjs compiling to wasm on Mac only. At least it's something.

**Comment by justjavac** [comment]
what about  https://github.com/justjake/quickjs-emscripten

**Comment by dsherret** [comment]
Any emscripten solution doesn't seem to allow compiling to a single .wasm file.

Anyway, I ended up implementing "process plugins" (not release yet), so that allows for things like https://github.com/dprint/dprint-plugin-prettier (uses https://github.com/vercel/pkg). I'm just going to close this, but would be nice to look into more in the future.
