### ISSUE TITLE
Illegal syntax formatting regression with rest arguments

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint#214]
**Describe the bug**

Illegal syntax formatting regression with arrow functions as property values.

Deno Version: master (pre 1.01)/dprint 0.18.0

**Input Code**

```ts
const bar = {
  foo: (param1: string, param2: string, param3: string, ...rest: string[]): void => {
    //
  },
};
```

**Expected Output**

```ts
const bar = {
  foo: (
    param1: string,
    param2: string,
    param3: string,
    ...rest: string[]
  ): void => {
    //
  },
};
```

**Actual Output**

```ts
const bar = {
  foo: (
    param1: string,
    param2: string,
    param3: string,
    ...rest: string[], // <-- illegal trailing comma for rest or binding params
  ): void => {
    //
  },
};
```

Refs: denoland/deno#5658

**Comment by dsherret** [comment]
@kitsonk just woke up. Looking into it right away.

**Comment by dsherret** [comment]
Occurred because function parameters are now being represented by new `Param` AST node and arrow function parameters are `Pat` (since they don't have decorators). Added a test specifically for this so it won't happen again.

**Comment by dsherret** [comment]
By the way, thanks for catching this @kitsonk!

**Comment by kitsonk** [comment]
No problem!  Glad it was a straight forward fix.
