### ISSUE TITLE
Async function with decorator and comment does not format correctly

### ISSUE THREAD

**Issue by SeanWong24** [dprint/dprint#220]
**Describe the bug**
When the input code has a function decorator and a comment before an async function, it behaves strange.

Version: x.x.x

**Input Code**

```ts
class Test {
    @A()
    // something
    async abc(){
        console.log("a");
    }
}
```

**Expected Output**

```ts
class Test {
    @A()
    // something
    async abc() {
        console.log("a");
    }
}
```

**Actual Output**

```ts
class Test {
    @A()
    async // something
    abc() {
        console.log("a");
    }
}
```

**Comment by dsherret** [comment]
@SeanWong24 thanks for reporting! I found a few other interesting edge cases while looking into this.
