### ISSUE TITLE
Add plugin update command

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#224]
This would open the current or specified config file and update all the plugins to the latest version. It would not bother doing any transformations on the plugin config though.

I'm thinking something like `dprint update-plugins` or `dprint update-plugins -c path/to-config.json`

**Comment by thomaseizinger** [comment]
As a more minimal version of this, can we just have a log printed if there are new plugins available on every invocation?

**Comment by thomaseizinger** [comment]
> I have the same problem. It would be really easy to implement this though because it could just be a find and replace in the file to start. I'm thinking `dprint config update` would be better than what I mentioned earlier.

For semver compatiable updates, that would be nice.
For breaking changes, making the user to the update is better IMO. You wouldn't want to leave things in a broken state after an "automatic" action.

**Comment by dsherret** [comment]
Oh, it would always be a manual update. They would just run `dprint config update` and that would do a find and replace in the file to update the plugins. I'm thinking in the future they could also do something like `dprint config add typescript` to add a plugin.

**Comment by thomaseizinger** [comment]
Leaving things in a broken state, even after `dprint config update` is not particularly nice. `cargo` for example does the same thing:

`cargo update` will bump all sem-ver compatible versions in the lockfile. Hence if crates respect semver, nothing will break as part of this. If I want to bump to a new major version, I need to update manually, or use something like dependabot.

`dprint` could follow this and only bump plugins to semver compatible versions as part of `dprint config update`. Also, FWIW, I would mildly prefer `dprint plugins update` over `dprint config update`.

**Comment by thomaseizinger** [comment]
> What do you mean by broken state?

If the config structure of the plugin changes in a backwards-incompatible way, then simply bumping the next major version leaves things in a broken state.

Looking forward to plugin registries and stuff :)
Is there like a roadmap somewhere on what things you are planning on building next?

**Comment by dsherret** [comment]
> If the config structure of the plugin changes in a backwards-incompatible way, then simply bumping the next major version leaves things in a broken state.

I'd rather the default path encourage users to upgrade to the latest plugin even if it breaks the configuration.

> Is there like a roadmap somewhere on what things you are planning on building next?

Nope. Haven't bothered developing a formal plan. It's more whatever I feel like working on any given day.
