### ISSUE TITLE
Extension for Editors?

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint#233]
I am not used this tool yet, but looks great, i looking extension for any of VS(Code/Codium), Sublime Text 3, (Neo/Oni)Vim.

Is there any extension available for any of these editors?

**Comment by lazarljubenovic** [comment]
Not sure what kind of tool you're looking for. What do you expect an extension to do?

There's an online tool [TS AST Viewer](https://ts-ast-viewer.com) which helps _a lot_. [This](https://ts-morph.com/setup/ast-viewers) page mentions an Atom plugin.

**Comment by dsherret** [comment]
Hey @dalisoft. Thanks! The formatting is working pretty well right now, but the surrounding infrastructure is lacking. I have basically finished working on the new CLI and my next step now is to work on the editor extensions.

My priority is for a VS code editor extension, which I'll do and figure out in #203 (will require some changes to the executable). Then after that it will hopefully be straightforward to add it for other editors.

**Comment by dalisoft** [comment]
Thanks. 
I happy to hear it’s in progress

**Comment by dsherret** [comment]
Closing this as there is a VSCode editor plugin now: https://marketplace.visualstudio.com/items?itemName=dprint.dprint

If anyone wants an extension for other editors, please open up a new issue per editor to help me prioritize work.

**Comment by dalisoft** [comment]
I created another issue for Sublime Text ;)
