### ISSUE TITLE
benchmark support

### ISSUE THREAD

**Issue by IWANABETHATGUY** [dprint/dprint#238]
Most people use `prettier` as code formatter, but we know that `prettier` is wrote in javascript, slower than rust, if we support benchmark between `dprint` and `prettier` , i think this could be a good reason for others to change `pretter` to `dprint`

**Comment by dsherret** [comment]
Yes, I’d like to (see #75). I’m currently making a big-ish change to the upcoming rust cli so it should be even faster once I’m done.

In summary, last time I checked it’s anywhere between 3-10+ times faster depending on the file size. With parallelization in the upcoming new rust CLI it is even faster.
