### ISSUE TITLE
playground crash

### ISSUE THREAD

**Issue by IWANABETHATGUY** [dprint/dprint#239]
![image](https://user-images.githubusercontent.com/17974631/84101362-5a6dde00-aa40-11ea-9942-de2f093dca83.png)
out of memory

**Comment by dsherret** [comment]
@IWANABETHATGUY did you do something specific to get that to happen? I’ve been making a lot of changes to the playground lately.

**Comment by dsherret** [comment]
I just did a basic test today and notice that there is a memory leak when I just keep switching back and forth between the plugins. I'll look into this later.

**Comment by IWANABETHATGUY** [comment]
great
