### ISSUE TITLE
Adopt an open source license for the CLI

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#243]
It’s very locked down at the moment. I’d like to adopt a copyleft opensource license.

**Comment by dalisoft** [comment]
GPL-3.0 or MPL license good-to-go. But, please trust me, if user wants use your product, uses, even doesn't tell you about this.
I'm also processed this way (hi some @nanoexpress users 😆, it's not adversiting). then i just opened license to apache-2.0, but making supporting premium (i got more free time than before, no requirements, more freedom).
But this is your project, do what you want.

**Comment by dsherret** [comment]
@dalisoft thanks for the suggestion! That’s cool you are doing that with nanoexpress. I think I’m going to go that way with [ts-morph](https://github.com/dsherret/ts-morph) because it’s a library, but I think for the dprint CLI it being MIT or Apache 2 is not as important because it’s a binary they execute rather than a library they link to. Right now [dprint-plugin-typescript](https://github.com/dprint/dprint-plugin-typescript) is MIT and will always remain MIT, but I think even if the CLI were GPL-3.0, commercial users wouldn’t care because they just run the binary standalone.

Perhaps I can somehow make the code GPL-3.0, but its use is still restricted by the terms of the current license? I don’t know. I’m not familiar enough with this stuff.

Goals:

1. Using the CLI on a project whose primary maintainer is a for-profit entity requires the purchase of a site license by the entity (means commercial users can use it for free on projects not primarily maintained by a for-profit company).
2. People should be able to freely make changes to the CLI, but are required to open source the work and the work’s use is still bound by point 1.

Anyway, my main goal is to get for-profit non-educational companies paying in order to drive development on this project, but at the same time I don’t want to be too restrictive about it. There is a possibility it might just become MIT.

**Comment by dalisoft** [comment]
@dsherret Yes, you right, there GPL-3.0 has limitations for us, you can use custom own license, that’s good variant too. 
Anyway, your project has potential, own special feature and we users need high-quality projects like yours. 
Supporting project development isn’t easy, sadly, not all users understand it. 
I hope you get enough financial support and i hope to see dprint with more sponsors and more users (more stars too 😉)

**Comment by Sonic12040** [comment]
@dsherret - I will admit, the requirement of a 500/mo license prevents me from recommending it in my enterprise environment. 

For my understanding, what are the selling points of dprint that justify the costs against free packages like Prettier?

**Comment by dsherret** [comment]
@Sonic12040 it’s important to note that’s the maximum rate and it’s for companies with 50+ developers, so that’s generally under $10/month/developer, which is not a lot for a company that size (similar to buying two nice coffee’s for each dev each month or even less if they have more developers).

Companies should try it out and do an assessment of whether it adds value to their business over other tools and also decide if they want to financially support this software’s future development.

**Comment by dsherret** [comment]
@Sonic12040 I've been thinking about ways to make this more accommodating and I decided to switch to a model where there is only a "sponsorship requirement" for companies and companies may sponsor at any of the rates provided. There are some recommended tiers based on company size, but ultimately they are able to decide how much they want to pay based on how much value they believe dprint will provide to their organization.

This should make it a lot easier for individual developers to pitch it to their organization.

**Comment by Sonic12040** [comment]
It definitely seems reasonable to me, though I would expect from an enterprise organization that, if it were going to make it past pitch, certain levels of documentation and support would need to be present, as well as direct comparisons to the other known units. Especially at larger enterprise levels, that decision will likely go to a purchasing department and not be directly in the hands of the developers.

In my own job, in any given one day, I'm likely to play with XSL, XML, Java, JS/TS, EJS, HTML, CSS, YML, JSON, React/JSX, and so my ideal formatter is going to cover all those use-cases (whether through extensible plugins or otherwise).

If I weren't already familiar with it, in addition to setup, I would want there to be decent documentation on CI integration (including but not limited to GitHub, Jenkins, Bamboo), and in addition to formatting checking the formatting and failing out if there are unformatted files, etc. We have to catch that one developer who does --no-verify in the CI/CD pipeline.

**Comment by dsherret** [comment]
@Sonic12040 thanks for the feedback! Yeah, I’m slowly working on most of those, but will prioritize it over the next few weeks.

**Comment by dsherret** [comment]
I'm thinking to just make the CLI MIT and keep the "projectType" field. Will probably do it tomorrow. I've started a company in a completely unrelated field and don't have as much time anymore for this (compared to before... will still work on this as much as I can).

**Comment by dalisoft** [comment]
@dsherret Congratulations with work on company. Please keep project as least on GPL-3.0 license, passive income is better than nothing even you started work in company

**Comment by Sonic12040** [comment]
Personally, I'd prefer MIT, because then I know we can use it.

**Comment by dsherret** [comment]
@dalisoft thanks! The company is going well so far.

I ended up going with MIT because it's just easier and hope companies will still consider sponsoring the project. Will be in v0.11

**Comment by dalisoft** [comment]
@dsherret I hope too.

**Comment by jasonkuhrt** [comment]
@dsherret just wanted to say I hope you get appropriate funding for your work here, and thanks for it!
