### ISSUE TITLE
Homebrew package?

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint#246]
I am today tried install, but i see there some ways which i do not like like `curl ??? | sh` or binary copy (it's acceptable, but easier way always better).

Is there any plan to add to Homebrew packages?
With Homebrew package there some benefits:
- Easy to install (just `brew install dprint`)
- Easy to update (just `brew update` to update all packages)
- Easy to remove (just `brew uninstall dprint`)

_I'm not member of Homebrew and it's not adversiting_

**Comment by dsherret** [comment]
Should be possible now via:

```shell
brew tap dprint/dprint
brew install dprint
```

I wasn't able to test it though because my Mac is doing updates. I'll need to automate this whole process on each release so I'll close this issue once that's done.

**Comment by dalisoft** [comment]
I didn’t see so fast updates and feature request implementation. 
Thanks a lot

**Comment by dsherret** [comment]
@dalisoft these just happen to align with the kinds of tasks I'm working on right now 😄

This is now completely implemented.
