### ISSUE TITLE
ESLint config/plugins compatibility?

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint#247]
Hi.

I'm wondering, is there a way use ESLint configs/plugins with **dprint**?
I love ESLint+Prettier+EditorConfig combo which makes my workflow easier.
I found alternative to Prettier (it's **dprint**), now i looking to ESLint alternative written in **Rust** language.

Thanks

**Comment by dsherret** [comment]
If you’re interested in an ESLint alternative you should check out https://github.com/denoland/deno_lint but I think there’s currently no way to use it outside deno.

**Comment by dalisoft** [comment]
Thanks @dsherret 
I will checkout this. I didn't knew about it

**Comment by dalisoft** [comment]
I can close issue because already found what i want
