### ISSUE TITLE
Should absolute files specified as a CLI arg be excluded if captured in an excludes pattern?

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#258]
For example, given the following config file at `C:\dev\.dprintrc.json`...

```jsonc
{
  // etc..
  "excludes": [
    "**/test"
  ]
}
```

...if a user specifies the following as a CLI arg...

```ts
dprint fmt -- C:\dev\test\file.ts
```

...should it format it?

**Comment by dsherret** [comment]
I would say yes because the user is being very explicit about formatting this file, but that's not the same behaviour as prettier. Additionally, right now, Deno's `./tools/format.py` script passes all the matching ts, md, js, tsx, json files in git as an absolute path and expects them to be excluded if ignored by a .prettierrc.

I think the current behaviour (what I expect) should remain and the `./tools/format.py` will have to work a little differently. Good news is that Deno's entire formatting process takes 5s now (3.75s if using the rustfmt plugin), while it previously took 17s when using Prettier.

**Comment by mrgrain** [comment]
lint-staged has a similar issue with all staged files being passed as absolute paths and then not excluded by dprint.
I'm not sure about the best approach to this, but wanted to flag it.

Maybe an additional option could help, something like `--always-exclude` or `--exclude-absolute`

**Comment by dsherret** [comment]
@mrgrain hmmm... yeah, perhaps copying what prettier has done here would be best. I think the current behaviour could occur if providing an `--excludes ""` flag to clear out the exclude patterns and if only one file is matched and ignored then it should output to stderr suggesting the user to provide `--excludes ""`.

Thanks for the feedback!

**Comment by mrgrain** [comment]
Whatever the feature is going to be, I like the idea of explicit output for unexpected config combinations. 🙂

**Comment by dsherret** [comment]
Ok, I investigated this and this is the current behaviour and what was talked about before is out of date.

@mrgrain if you specify an absolute path as a CLI arg then it should format it regardless of the excludes patterns. Also, you can clear out the excludes patterns by specifying `--excludes=""`.

Let me know if something is not working like I've just described. I just added some tests for this as it wasn't properly tested.

**Comment by dsherret** [comment]
To answer the question in the issue, I believe so. Opened #474
