### ISSUE TITLE
fish shell dprint execution error

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint#266]
Hi @dsherret 

I'm still not used dprint, but last time my vscode gives error `/usr/local/dprint` is not executable and/or permission error.

Then recently i tried execute it directly, but i got error

```
❯ dprint
Failed to execute process '/usr/local/bin/dprint'. Reason:
exec: Exec format error
The file '/usr/local/bin/dprint' is marked as an executable but could not be run by the operating system.

~ 
❯ 
```

OS: macOS 10.15.6
dprint: 0.6.3

Brew info

```
❯ brew info dprint
dprint/dprint/dprint: stable 0.6.3
Pluggable and configurable code formatting platform.
https://github.com/dprint/dprint
/usr/local/Cellar/dprint/0.6.3 (3 files, 8.8MB) *
  Built from source on 2020-07-19 at 01:24:22
From: https://github.com/dprint/homebrew-dprint/blob/HEAD/Formula/dprint.rb

~ 
❯ 
```

Before on some executables sometimes helped `chmod +x /usr/local/bin/dprint`, but for dprint it did not help.
I hope you can look and fix.

Thanks

**Comment by dsherret** [comment]
@dalisoft thanks for reporting. It looks like the homebrew release is broken.

This is definitely wrong 😅

![image](https://user-images.githubusercontent.com/1609021/88009637-01827280-cae1-11ea-9a7f-81d4e858f387.png)

I must have broke it recently.

**Comment by dsherret** [comment]
@dalisoft ok, I manually fixed this. I was able to get it working again on my mac by running:

```
brew remove dprint
brew tap dprint/dprint
brew install dprint
```

I'm going to leave open this issue though because I will investigate sometime before the next release why it's happening. It's strange because there weren't really any changes to the CI file when this started happening. The file gets created here, but now it's basically an empty tar.gz file: https://github.com/dprint/dprint/blob/2ee5f6247f0c06095fa75e7e7b1183fdc681592d/.github/workflows/ci.yml#L114

Anyway, I'll look at this later. Thanks once again!

**Comment by dalisoft** [comment]
I seem not only your package was broken, also fnm and other some packages was broken. Found when tried install my apps playbook on new linux machine.
Thanks for quick fix, you always fix everything very fast, i can say you fastest author.

**Comment by dsherret** [comment]
That’s very strange. Maybe it’s a github actions problem.

Oh, are you using homebrew with linux? I think this only works on mac at the moment.

**Comment by dalisoft** [comment]
Yes. i use Homebrew in Linux and works fine (Casks does not work).
I also before think it does not work, but seems work fine.

Because of 8-10 great tools including `dprint` i use Homebrew on Linux, if these tools will be available in APT, i switch immediately

**Comment by dalisoft** [comment]
Maybe you right, it's may be Github Actions bug

**Comment by dalisoft** [comment]
```
brew remove dprint
brew tap dprint/dprint
brew install dprint
```

these steps did not help, same error

**Comment by dsherret** [comment]
Ok, that must be that I didn’t add the linux package to homebrew. I’ll do that later.

**Comment by dalisoft** [comment]
I also understand later.
I forgot mention i use Homebrew on both macOS and Linux platform.

for macOS your [trick](https://github.com/dprint/dprint/issues/266#issuecomment-661617936) helped, thanks

so this is issue can be closed

**Comment by dsherret** [comment]
I'm going to wait on closing this issue. It should be fixed once I reference the linux binary somewhere.

**Comment by dsherret** [comment]
I believe this should be fixed now by removing the dprint/dprint tap (`brew untap dprint/dprint`) and installing dprint via `brew install dprint`.
