### ISSUE TITLE
[Feature Request]: APT Support for Linux?

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint#267]
Hi @dsherret 

Is there any chance to APT support?

Thanks

**Comment by dsherret** [comment]
Not at the moment. I'd need to figure out #243 first.

I'm going to close this one as "on hold" for now, but in the future it's something I'd like.

**Comment by dalisoft** [comment]
For Linux currently i use this command until there will be APT support

```bash
wget -qO- https://github.com/dprint/dprint/releases/latest/download/dprint-x86_64-unknown-linux-gnu.zip | busybox unzip - && mv dprint /usr/local/bin/dprint
```

**Comment by dalisoft** [comment]
Any news about this ?
