### ISSUE TITLE
Upload coverage reports to CodeCov

### ISSUE THREAD

**Issue by trivikr** [dprint/dprint#275]
**Is your feature request related to a problem? Please describe.**
Coverage reports are not available for dprint when viewed at https://codecov.io/gh/dprint/dprint

**Describe the solution you'd like**
Coverage reports are uploaded to Codecov on each git push https://codecov.io/gh/dprint/dprint

**Additional Context**
Created this issue after visiting swc: https://github.com/swc-project/swc/issues/917

**Comment by dsherret** [comment]
It's a good idea. I looked into this a bit for [dprint-plugin-typescript](https://github.com/dprint/dprint-plugin-typescript) and found the codecov instructions not very helpful and ran into some errors, so I'm going to hold off on doing this for now.

**Comment by dsherret** [comment]
Actually, I think I'm not going to bother with this. It's just another thing to maintain and I think the testing has been going ok on its own without having coverage.
