### ISSUE TITLE
Make it easy for people who don't have dprint installed to format projects that use dprint

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#292]
Need to make it easy for people to setup their projects so users can just come in and do, for example, `yarn format` and it just works.

If anything, this might just be setup instructions.

**Comment by dsherret** [comment]
The current state of things is quite poor, so I've started working on https://github.com/dsherret/bvm

I'm going to try to make the distribution of that super easy then people can install dprint via it.

**Comment by Auxx** [comment]
`$ npx dprint check` and `$ npx dprint fmt` work here just fine, but that's only applicable to node/web devs.

**Comment by joscha** [comment]
we're using `nix` - we have a custom setup that manages the plugins via nix as well, but there is an official version for core available here: https://github.com/NixOS/nixpkgs/blob/a3c4956cf9cb921d61b4a5c30df6ef1c07d2fae4/pkgs/development/tools/dprint/default.nix (currently at 0.15.1)

**Comment by adrian-gierakowski** [comment]
Nix is the way to go unless you need native windows support (without using WSL).

Here’s a project which make adopting nix trivial: https://devenv.sh/

**Comment by dsherret** [comment]
Going to close this one because it's easier nowadays and we should maybe open targeted issues for certain scenarios.
