### ISSUE TITLE
Installation issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by tsopeh** [dprint/dprint#303]
Version: 0.9.1

When running the installation script, the process exits with no output. 
I tried pasting a few `echo`s and figured out that the installation gets canceled on `pkill` command.

https://github.com/dprint/dprint/blob/299521053c93e414ee02bee3ecd21fd380d46003/website/assets/install.sh#L39

Since I've never ran `dprint` before, I just removed this line and installation seems to work fine. I added exports to `.bash_profile` and ran `dprint --help` which worked alright.

**Comment by lazarljubenovic** [comment]
The same happens to me on Ubuntu 18.04.5. Just an exit without any output.

**Comment by dsherret** [comment]
Thanks a lot @tsopeh for opening this! I obviously did not properly test this when adding that line. I've opened #304 to help prevent this in the future.
