### ISSUE TITLE
Deno bindings aren't working correctly

### ISSUE THREAD

**Issue by Vehmloewff** [dprint/dprint#309]
It appears that `createStreaming` throws an error in Deno.

```
error: Uncaught TypeError: WebAssembly.compile(): Argument 0 must be a buffer source
```

**Reproduction**

```
$ deno run --allow-net https://gist.githubusercontent.com/Vehmloewff/dfc296f8bf0c02a1c75de39f0d263dd0/raw/df0090e61dd5d567e3ccd5796e1ec7fafe50cb8d/mod.ts
before createStreaming
error: Uncaught TypeError: WebAssembly.compile(): Argument 0 must be a buffer source
```

**Comment by dsherret** [comment]
Hmmm... thanks for reporting this! It occurred when Deno started supporting `WebAssembly.instantiateStreaming`. There's an open issue here in Deno https://github.com/denoland/deno/issues/7259 -- until they fix it, I'll implement a workaround.

**Comment by dsherret** [comment]
Will be fixed on the site once the CI [completes](https://github.com/dprint/dprint/actions/runs/294580035). Also opened #310.

**Comment by Vehmloewff** [comment]
Wow, thanks for the speedy fix @dsherret, you're a blessing to your family!

**Comment by dsherret** [comment]
Note that there is a new Deno module (https://deno.land/x/dprint/mod.ts) and node.js package for this:

https://github.com/dprint/js-formatter
