### ISSUE TITLE
Upgrade wasmer to 1.0 once released

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#318]
It's currently in 1.0-alpha. I'd like to upgrade to the new version asap because it's much better.

Work is basically done here: https://github.com/dprint/dprint/tree/newWasmer

Todo:

- [x] Have a way to automatically clear cached plugins on upgrade due to new wasmer (I don't know if deserialization will work so I'd rather just clear everything)

This will resolve #227

**Comment by syrusakbary** [comment]
Just seen this. Deserializing in Wasmer 1.0 will only work with serialized modules with Wasmer 1.0 (we upgraded the serialization structure).

**Comment by dsherret** [comment]
@syrusakbary cool, thanks for letting me know and that’s what I suspected. I’m just going to clear the serialization cache whenever upgrading wasmer to be safe as it’s no big deal to do.

Thanks for the excellent work on wasmer! I’m excited for the new release.
