### ISSUE TITLE
Format plugin request: toml

### ISSUE THREAD

**Issue by thomaseizinger** [dprint/dprint#321]
It would be nice if dprint were able to format toml files.

In particular, I am looking for sorting entries within a table so that the entries within `[dependencies]`of my `Cargo.toml` files are sort alphabetically and thus reduce the chances of merge-conflicts if they are edited in parallel!

I might get around to implementing this myself. Will let you know on this issue if I do!

**Comment by thomaseizinger** [comment]
I've got an initial version here: https://github.com/thomaseizinger/dprint-plugin-cargo-toml

Let me know if you are interested in including this in the organization!

For the formatting rules I roughly followed this guide: https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/cargo.md

Specifically, the plugin:

- sorts entries of the `package` table (with `name` and `version` always being at the top and `description` always at the bottom)
- sorts entries in `dependencies` and `dev-dependencies` tables
- respects comments within those entries as long as they are on the same line

This the bare minimum that I found useful for an initial version.

**Comment by dsherret** [comment]
@thomaseizinger wow, that is awesome! Yes, this would be great! I'm really glad you were able to do this seemingly quite easily and that the `dprint_core::generate_plugin_code!();` is doing its job.

I'm super super busy this week and next (working crazy hours for a work-related release). I'll set a reminder to come back to this soon. It would be good if I updated plugins.dprint.dev to act like a redirect service so you could automatically have it point at your github repo, but I think for now you can just specify `https://github.com/thomaseizinger/dprint-plugin-cargo-toml/releases/download/0.1.0/cargo-toml-0.1.0.wasm` in .dprintrc.json and it should just work. In the future, it would be nice to bring this into the org 🙂

**Comment by thomaseizinger** [comment]
@dsherret Thanks! Yes it was reasonably easy to write the plugin :)
Although I think generating the code with a proc-macro and using traits for the functions that should be exposed would be a bit nicer because then their signatures are easier to get right. The example was a bit outdated so I had to follow the compile-errors to get them right! Wasn't a huge problem though :)

I am already using the plugin (https://github.com/comit-network/comit-rs/pull/3380) and it works great!
Might file some issues upstream (toml-parse) to allow for more customization. Also, I am not very experienced in manipulating ASTs so there are probably nicer ways of doing things 😁

I am happy to move this into the org, there is no rush though!

**Comment by dsherret** [comment]
This is actually basically almost done now here: https://github.com/dprint/dprint-plugin-toml (basically no configuration though)

I submitted a PR to taplo (parser) to get it building under Wasm and it should be good to try out. After that, we can see about merging in https://github.com/thomaseizinger/dprint-plugin-cargo-toml -- I think it could be a pre-processing pass for Cargo.toml files and then after it can be sent to the IR generation for formatting with certain configuration (dprint-plugin-toml/src/parser/parser.rs).

**Comment by dsherret** [comment]
This is now available for use in the CLI: https://github.com/dprint/dprint-plugin-toml/releases

It's very new, so let me know about any bugs or configuration you would like here: https://github.com/dprint/dprint-plugin-toml/issues

Opened #370 to eventually add this to the website and `dprint init`.
