### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by chenrui333** [dprint/dprint#323]
👋  heads up, I have filed [a PR](https://github.com/Homebrew/homebrew-core/pull/65924) to introduce the homebrew support for this wonderful tool.

**Comment by dsherret** [comment]
Hey @chenrui333, thanks for doing that! At the moment I've just had a tap [here](https://github.com/dprint/homebrew-dprint).

That said, I'm not sure it's allowed in homebrew/core because it does not have an opensource license applied to it at the moment (see #243 ...I will get around to it eventually once I figure it out which one I want to go with).

> Our policy is that formulae in the core tap (homebrew/core) must be open-source with an Debian Free Software Guidelines license and either built from source or produce cross-platform binaries (e.g. Java, Mono). Binary-only formulae should go to homebrew/cask.

https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by chenrui333** [comment]
I thought the codebase is with Apache-2.0, no?

**Comment by chenrui333** [comment]
If that is not the case, then I probably need to close my homebrew-core PR :(

**Comment by dsherret** [comment]
Unfortunately no. Some libraries within are MIT and all the plugins, but the CLI itself is under a custom license. https://github.com/dprint/dprint#notes

I'll find an appropriate license for the cli soon.

**Comment by chenrui333** [comment]
You can potentially dual licensed the solution though, one for community, one for enterprise, there are many homebrew formulae already doing that.

**Comment by dsherret** [comment]
Hey @chenrui333, the CLI is now MIT in 0.11.0 🙂

**Comment by chenrui333** [comment]
@dsherret thanks for doing this!!

**Comment by chenrui333** [comment]
Now the PR has been merged, close this issue now.

**Comment by dsherret** [comment]
Awesome. Thanks a lot @chenrui333!

I'm not sure what's going on in #328, but will look into it soon. I'm super busy at the moment unfortunately (working today even, but with good reason).

**Comment by chenrui333** [comment]
I think ti s more like `darwin-arm64` target missing in the compiler chain somewhere.

**Comment by chenrui333** [comment]
@dsherret I also update the docs for reflecting the new brew installation option. :)
