### ISSUE TITLE
Thoughts on the default dprint configuration filename(s)

### ISSUE THREAD

**Issue by ChristianGrete** [dprint/dprint#342]
Dot files are there to hide distinctive program-specific files and folders in home directories that are not meant for common use cases. Rc files in home directories are usually dot files and used to configure a program by setting flags or environment variables and/or by running a bunch of commands when launching that program. They are rather meant to initialize how a program integrates and internally behaves in a certain environment than telling a program how it should process a command.

Using a fictional rich text editor program as an example, its Rc file would tell that program which toolbars should be shown on startup, but it would not set the font or color in documents. It does not tell the program how to edit files but it defines parameters on how editing is done.

It annoys me that in the Node.js world with `cosmiconfig` anything goes in hidden Rc dot files. In a lot of cases even without any file extension. And it even more annoys me that this seems to be adopted in the Deno and Rust context as well.

I am totally fine with a `.dprintrc.json` file as long as it contains a site-specific default configuration and lives in the `$HOME` directory. Why do you want a project-specific configuration file to be hidden in Unix-like systems? And when using the non-hidden `config/` directory, why would you even want to make it a hidden file in there as well?!

And why do you call it an Rc file? Just because this became a somehow standard in Node.js projects? What speaks against a `config/dprint.json` or a `dprint_config.json` file for example? Looking at TypeScript, they simply use `tsconfig.json`. They are not forcing anyone to show hidden files in file browsers or editors. And they are also not claiming it to be a fancy unix-style runcom that is actually just an object of command options that nobody wants to pass as single command line options to the program... Same with Cargo: They use a `Cargo.toml` manifest file in projects and `$HOME/.cargo/config.toml` for a global configuration, which is what Rc files should do as well.

For the sake of Deno and Rust, please stop using that `.cr*prc` pattern. [Even if Deno is currently using this pattern in its project (#257)](https://github.com/dprint/dprint/issues/257). Thank you. 😉

**Comment by ChristianGrete** [comment]
Btw. `rustfmt` allows both a `rustfmt.toml` and a `.rustfmt.toml` which makes totally sense as they also allow those files to be placed in parent directories or in the `$HOME` directory where you might want to hide these files. And they also do support the `dirs::config_dir` (e.g. `$HOME/.config/rustfmt/rustfmt.toml`)...

**Comment by dsherret** [comment]
I'll respond back later, but just quickly... the other day I saw deno lint (dlint), did `.dlint.json` and thought that would be better. Overall, I think you raise some good points and thanks for the feedback (again, will respond later).

Basically, this isn't a subject I have thought deeply about and was just somewhat following what I saw done in some other tools.

**Comment by Alhadis** [comment]
Just to clarify, a RC is typically used when executing an _interactive_ command. E.g.,
- Login shells: `.kshrc`, `.bashrc`
- Text-editors: `.exrc`, `.vimrc`
- REPLs: `.irbrc`
- Multiplexors: `.screenrc`
- System startup scripts: [`/etc/rc`](https://github.com/openbsd/src/blob/2434f2999afc8b290f301bcb683cb380118e56bc/etc/rc)

Regarding filename choices:

1.	**Use a clear, _visible_ filename which includes a recognisable file-extension.**   
`dprint.json`, `dprint.toml`, and `dprintconfig.yml` describe both the file's use and its syntax. Conversely, `.dprintrc` could be any number of formats, and not every user knows to to ignore `rc` suffixes in filenames.

2.	**Provide a CLI option for specifying a config's location.**  
	When omitted, the CWD is searched for the default config name. If it isn't found, inform the user about it and terminate with an error code.

	Don't try to be "smart" by scanning parent directories for a missing file. Users are better off passing `-c ../dprint.toml` from a subdirectory instead of being expected to learn some [complicated lookup algorithm](https://nodejs.org/dist/latest-v15.x/docs/api/modules.html#modules_loading_from_node_modules_folders).

3.	**Support only *one* format for your config.**  
	TOML is a good choice. JSON and XML are not.

	Sticking to one format also spares you the headache of having to distinguish formats based on a file's contents or extension.

4.	**Don't use more than one default filename.**  
	Pick `dprint.config.json` or `.dprint.json`, not both.

<hr/>

I apologise if that was a bit long-winded. Naming a file isn't [rocket surgery](https://i.pinimg.com/originals/03/fb/48/03fb48816c573b659e81bd73129c28cc.jpg), but Node devs have a habit of copying bad filename choices without question, for the exact same reason you gave earlier:

> Basically, this isn't a subject I have thought deeply about and was just somewhat following what I saw done in some other tools.

**Comment by dsherret** [comment]
I'm leaning towards the following:

1. Remove support of configuration file in `config` sub directory.
2. Still want ability to go up the ancestor directories looking for a configuration file when a configuration file does not exist in the cwd. I find this really useful when I'm in a descendant directory and want to format stuff... basically, a dprint configuration file should apply to its current directory and all descendant directories, so if you are in one of those descendant directories you should be able to run a command and it will use that configuration file.
3. Rename `.dprintrc.json` to `dprint.json`. For a few versions, support `.dprintrc.json`, but show a warning about it.

**Comment by ChristianGrete** [comment]
> 2. Still want ability to go up the ancestor directories looking for a configuration file when a configuration file does not exist in the cwd. I find this really useful when I'm in a descendant directory and want to format stuff... basically, a dprint configuration file should apply to its current directory and all descendant directories, so if you are in one of those descendant directories you should be able to run a command and it will use that configuration file.

When looking for configuration files in ancestor directories, you might want to support a dot file filename as well (`.dprint.json`) as it does make a huge sense to hide global config files e.g. in the `$HOME` directory where users probably don't want to see these kind of files...

**Comment by dsherret** [comment]
@ChristianGrete is that a use case some people might do? I'm not sure it should be encouraged. The main use case I've been thinking about is having a per-repo configuration file or in rare cases having a configuration file in a sub directory as well that overrides the main configuration file or extends it by specifying something like `"extends": "../../dprint.json"` in their config file.

By the way, I think it's good to be opinionated about the configuration file because it makes the tooling a lot simpler... that said a `--config` flag does exist at the moment, but it's not supported by the tooling that currently exists (ex. the vscode extension doesn't support specifying a configuration file manually).

Also, thanks for all of your feedback on this @ChristianGrete and @Alhadis! I appreciate it.

**Comment by ChristianGrete** [comment]
@dsherret Yeah, it is definitely not a common use case for a formatter tool that is installed locally (as a dev-dependency) in a project and I like the idea of keeping it as simple and opinionated as possible. But when looking up all the ancestor directories, `dprint` will in most cases go through the `$HOME` directory. And when thinking of a binary file that is installed globally on a machine (e.g. in `/usr/local/bin`), it does make sense to provide a user-wide configuration, which made me think of both a hidden dotfile and a regular file... So personally as the simplest solution I'd say it should just lookup the current working directory for a config file – but this file could be optionally extended by another file from whatever specified path (or by multiple paths?). 😊

**Comment by dsherret** [comment]
This is now released in 0.12.0. Thanks agian for the feedback!
