### ISSUE TITLE
Download files via a proxy

### ISSUE THREAD

**Issue by TiceCosmos** [dprint/dprint#346]
Files cannot be downloaded in some areas.
```
Message: Error downloading https://github.com/... . Status: 500
```

**Comment by dsherret** [comment]
Yes. I remember Deno had this issue with users in China. It would be good to copy their implementation: https://deno.land/manual@v1.4.0/linking_to_external_code/proxies

**Comment by dsherret** [comment]
This will read from the `HTTPS_PROXY` and `HTTP_PROXY` environment variables in 0.13.0.
