### ISSUE TITLE
🙏🏻 [feat/req] Allow alternative default configuration file with leading `.`

### ISSUE THREAD

**Issue by rivy** [dprint/dprint#351]
IMO, a format configuration file is a developer detail, divorced from the actual code of a project. With such accessory files, I think it best to "hide" them as dotfiles to signal their accessory nature and minimize any distraction from the "actual" project code. For example, I'm using **`.dprint.json`** (leading `.`) as the configuration for several Deno repositories. It would be nice to allow the CLI tool to automatically use such files as an alternate to the now-default **`dprint.json`** file for low-effort configuration.

Thanks for the consideration.

**Comment by dsherret** [comment]
See discussion in #342.

That said, I’m open to having a secondary default configuration file that is `.dprint.json` as it’s not much trouble and will satisfy people who prefer it to be hidden such as yourself.

**Comment by rivy** [comment]
> See discussion in #342.

👍🏻 
 
> That said, I’m open to having a secondary default configuration file that is `.dprint.json` as it’s not much trouble and will satisfy people who prefer it to be hidden such as yourself.

Thanks for the consideration (an the extremely rapid responses). 😄

**Comment by rivy** [comment]
Thanks!
