### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by bpierre** [dprint/dprint#352]
I was wondering if it would be possible to publish dprint on npm?

A standard practice for web projects to format code in a reproductible way is to have `prettier` in the `devDependencies`, and to have a `.prettierrc` in the project itself. It makes it possible to format code without any extra step for developers, e.g. in a pre-commit hook, and also to make sure the same version is being used by everyone.

I know `dprint` is publishing binaries, which is not well supported by npm, but it can be done in a way that is manageable. [esbuild](https://github.com/evanw/esbuild) (written in Go) is publishing a binary for Linux / Windows / macOS, and I adapted it myself for [esbuild-config](https://github.com/bpierre/esbuild-config/tree/main/npm), written in Rust. See also [the build action](https://github.com/bpierre/esbuild-config/blob/6e82ce4e064cac97fe532718f510ccb4ef4b0e90/.github/workflows/build.yml).

I saw that dprint used to be published on npm (it’s currently [marked as deprecated](https://www.npmjs.com/package/dprint)), so I imagine this has been discussed somewhere, but I couldn’t find it.

Let me know if I can help in any way to make this happen :slightly_smiling_face:

**Comment by dsherret** [comment]
Investigated this and I'm going the route of copying what vscode-ripgrep (https://github.com/microsoft/vscode-ripgrep/tree/main/lib) does and download from github releases.

**Comment by dsherret** [comment]
This is released now with 0.14.0. Might take a few hours for npm's caches to update from it being previously deprecated though.

**Comment by bpierre** [comment]
Awesome! Thank you :pray:
