### ISSUE TITLE
Using --stdin adds empty newline

### ISSUE THREAD

**Issue by disrupted** [dprint/dprint#353]
Version: 0.12.0

Hey there! Just started using dprint (it's so fast!).
I noticed a difference in the output between running `dprint fmt file.tsx` and `cat file.tsx | dprint fmt --stdin tsx`. The latter adds an empty newline to the output. I also tried it with a markdown file and it was the same so I am assuming this is not plugin-related.

edit: just tried it out with deno fmt and there it doesn't happen, e.g. `cat file.md | deno fmt --ext md -`

**Comment by dsherret** [comment]
@disrupted thanks! I must have broke this when doing some improvements to the logging.

**Comment by disrupted** [comment]
@dsherret thanks for the quick fix!
