### ISSUE TITLE
Add full filename match plugin

### ISSUE THREAD

**Issue by TiceCosmos** [dprint/dprint#362]
I use meson to build cpp project.

Meson file name is `meson.build`, `meson_options.txt`.

Get plugin by `.build`, `.txt` extensions is not friendly.

Is it feasible to add features?

[dprint/src/plugins/plugin.rs](https://github.com/dprint/dprint/blob/main/crates/dprint/src/plugins/plugin.rs#L6)
```rust
...
/// Gets the file fullnames.
fn file_fullnames(&self) -> &Vec<String>;
...
```

**Comment by dsherret** [comment]
Yes, I think this is a good idea.

This would be good for @thomaseizinger's https://github.com/thomaseizinger/dprint-plugin-cargo-toml too.

**Comment by dsherret** [comment]
@TiceCosmos would you be able to outline your use case a bit more so I can better understand it? Are you formatting only the meson.build and meson_options.txt files?

**Comment by thomaseizinger** [comment]
> Yes, I think this is a good idea.
> 
> This would be good for @thomaseizinger's https://github.com/thomaseizinger/dprint-plugin-cargo-toml too.

Yep that would be useful.

On that note, it happened multiple times to me that I added a plugin and forgot to update the `include` array in the config file. A plugin always knows what it wants to format right? Have you considered removing `include` from the config and let the plugins determine that?

It would go well together with this feature if the plugin can just specify a glob!

**Comment by TiceCosmos** [comment]
> @TiceCosmos would you be able to outline your use case a bit more so I can better understand it? Are you formatting only the meson.build and meson_options.txt files?

Yes, only meson.build and meson_options.txt

**Comment by dsherret** [comment]
Implemented in #363 (thanks @TiceCosmos!)

I also made one small change to rename `exact_file_names` to just `file_names` because after thinking about it a bit more I don't think the distinction is necessary. https://github.com/dprint/dprint/commit/5658afe6df142f816dd05405848fc8844dc121da

**Comment by disrupted** [comment]
Is there already documentation on how to use this setting? I would like to configure it for https://github.com/thomaseizinger/dprint-plugin-cargo-toml

**Comment by thomaseizinger** [comment]
> Is there already documentation on how to use this setting? I would like to configure it for https://github.com/thomaseizinger/dprint-plugin-cargo-toml
> 
> edit: figured it out.
> 
> in dprint.json
> ```json
> ...
> "includes": ["**/*.{ts,tsx,js,jsx,json,md}", "Cargo.toml"],
> ...
> ```

I am pretty certain that this has nothing to do with the feature being discussion here :)

What your config line does is describing to dprint, what files should be formatted.

What this issue is discussing is for _plugins_ to not just be per file extension but for individual files only. It does essentially remove the need for code like this:
 https://github.com/thomaseizinger/dprint-plugin-cargo-toml/blob/3ed018eb74bf24be061b0db5d97bee5d13e947fa/src/lib.rs#L60

(Note to self: Update the plugin to the latest dprint-core)
