### ISSUE TITLE
What Does the projectType Setting Actually Do?

### ISSUE THREAD

**Issue by zicklag** [dprint/dprint#364]
Hey there, I was just looking into this and I was a little confused when doing a `dprint init` what the question about the kind of project I'm using it for would actually change. Is it used in telemetry so you can find out which project use what tier or does it change the functionality of `dprint` at all? Is it purely informational?

Whatever it's for it would be nice to have an explanation of that in the docs, and probably in the `dprint init` output, too. It's just a little confusing because I couldn't intuitively figure out what difference it was making and why it was asking me.

It would make total sense to have like a "if you use dprint for a commercial project please consider sponsoring development", but when it just asks me what kind project I'm using, I don't know what it's going to do with that info.

**Comment by dsherret** [comment]
Removed in https://github.com/dprint/dprint/commit/f41d1fa50d68fd0d0c1a7def9fb6cbae25b0ddc6
