### ISSUE TITLE
npm install fails on non-Linux OSs

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint#368]
On Windows:

```
> node ./install.js

Get-FileHash : The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\SNIP\node_modules\dprint\install.ps1:18 char:17
+ $ZipChecksum = (Get-FileHash $DprintZip -Algorithm SHA256).Hash
+                 ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-FileHash:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dprint@0.15.2 postinstall: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dprint@0.15.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2021-06-16T17_33_45_544Z-debug.log
```

And on macOS:

```
> node ./install.js

#=#=#                                                                         

######################################################################## 100.0%
##############                                                            20.1%
##############################################                            63.9%
######################################################################## 100.0%
/Users/runner/work/SNIP/node_modules/dprint/install.sh: line 14: sha256sum: command not found
child_process.js:674
    throw err;
    ^

Error: Command failed: /Users/runner/work/SNIP/node_modules/dprint/install.sh 0.15.0 18f43b2a861b5a9e3d27f4ff911449c15cfbf518f2a43e51b8d61d36fa787f7a
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.<anonymous> (/Users/runner/work/SNIP/node_modules/dprint/install.js:34:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 1338,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dprint@0.15.2 postinstall: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dprint@0.15.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2021-06-16T17_35_30_026Z-debug.log
```

The scripts seem to assume that certain tools exist and are runnable at the shell, but that's not generally true.

I think it would make sense to implement these scripts directly in JS; as far as I can tell, they just download and do a checksum, both of which can be done in Node with fetch and the crypto module (or, other third party libs). (Or, some other method to get the binary, a la esbuild's publishing of binaries or a compiled wasm module.)

Forgive my slew of issues; I found this project reading threads about prettier's performance as I have a huge TS file that takes many seconds to format (and thus makes VS Code very unhappy on save) and I'm finding little things...

**Comment by dsherret** [comment]
Thanks! Yeah, I only added an npm deployment recently and it was a fast initial implementation based on the existing install scripts. Looks like Get-FileHash doesn’t work in old versions of powershell.

**Comment by dsherret** [comment]
I'm curious what version of powershell that is. Powershell v5 that has `Get-FileHash` came out in 2016. I think v4 is end of life.

**Comment by jakebailey** [comment]
This is from GitHub Actions, so it's whatever they have. Based on https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md it should be v7. Related are:

https://github.com/PowerShell/PowerShell/issues/8635
https://github.com/PowerShell/PowerShell/issues/6850
https://github.com/actions/virtual-environments/issues/225

Which makes it seem like it's a difference between PowerShell and "PowerShell Core" and some module loading oddity.

**Comment by dsherret** [comment]
Interesting. Good to know and thanks for the links! Will fix this soon.

**Comment by dsherret** [comment]
Ok, just tested on all three operating systems and the npm package 0.15.3 seems to work.

Thanks again for reporting! I ended up keeping a lot of the current code and just shifted the checksum verification to node. In order to move more code to node, I would have to install extra packages to do stuff like showing progress bars on download and unzipping a zip file. Also, no fetch in node, so downloading without a library is a pain. I'd rather it have as little number of dependencies as possible.
