### ISSUE TITLE
Allow dynamic resolution of plugins

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#372]
We'd like to make the plugins available via https://nixos.org/ which means that at source-time (e.g. when the `dprint.json` is checked into the repo) we don't know the local file path of the plugin, yet.

My current thoughts are:

* start an HTTP server on localhost and provide plugins with a stable path but manage the served version via nix (this idea would probably work but feels quite clunky)
* allow references to a custom resolver of sorts (e.g. some active code (wasm?) that can call out to an external data source to provide the real plugin? e.g. `plugin-proxi.wasm?real=typescript` -> returns the typescript wasm plugin. What would be even better is to allow a plugin source script to return a list of plugins to dprint, so we could do: `https://stable/url/plugin-provider.wasm` that returns a list of URLs and/or binary stream of wasm plugins.

This does sound a bit crazy, I know.

any other ideas?

**Comment by joscha** [comment]
Current thinking to get it working with the current state of dprint:

wrap the dprint binary with code that writes the plugins into a non-source-controlled `./.dprint/plugins/...` location and reference that one from the config.

**Comment by joscha** [comment]
Went with the `--plugins ...` env flag for now. Will close this.

**Comment by joscha** [comment]
Actually, reopening this. It turns out that dprint always displays the help page when calling it via:


```
dprint --plugins ... <subcommand>
```
no subcommand works with this, however NixOS' default location to add the flags are behind the executable: 

https://github.com/NixOS/nixpkgs/blob/3af210329f8dcbcaac23a9553a21acd5628a672f/pkgs/build-support/setup-hooks/make-wrapper.sh#L110

This results in a wrapper that looks like:

```
#! /nix/store/pcjan45rssdn01cxx3sjg70avjg6c3ni-bash-4.4-p23/bin/bash -e
exec -a "$0" "/nix/store/8v75xjwgmf72w5z2xj88a2bl1a1nv85h-dprint-with-plugins-0.0.4-canva-pre/bin/.dprint-wrapped"  --plugins /nix/store/94m3xrclpn29k4isrf6zjg0mlbyxs9ja-typescript.wasm "$@"
```

simplified:
```
#! /bin/bash
exec -a "$0" "/path/to/original/dprint"  --plugins /dynamic/path/to/any/plugin.wasm "$@"
```

For this to work, I'd need to prepend the argument:
```
#! /bin/bash
exec -a "$0" "/path/to/original/dprint" "$@" --plugins /dynamic/path/to/any/plugin.wasm
```

which is not something that nix currently supports.

**Comment by dsherret** [comment]
It seems to work with the flag appended after the sub command:

```
dprint fmt --plugins https://plugins.dprint.dev/typescript-0.30.0.wasm https://plugins.dprint.dev/toml-0.1.2.wasm
```

I think maybe clap requires that order because the `--plugins` flag takes multiple urls.

I think probably providing the plugins this way is the way to go, but I don't understand this use case at all. I'm going to look into all this in more detail over the weekend.

**Comment by joscha** [comment]
I ended up introspecting whether there is a command passed or not and only in the case when there is, passing the `--plugins` flag. Not perfect but seems to work. Will close this for the time being.
