### ISSUE TITLE
Support using dprint on a readonly file system

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#375]
As title. From #374. I assume for using `dprint check`.

```
Error creating cache directory: Error("Error creating directory /homeless-shelter/Library/Caches/dprint/cache: Read-only file system (os error 30)")
```

cc @joscha

**Comment by dsherret** [comment]
Perhaps instead of implementing something complex for this, it could instead error and suggest to the user to run with `--disable-plugin-cache` (#376). I think I would prefer this.

**Comment by dsherret** [comment]
@joscha I looked into this a bit and it does not seem practical to support a readonly file system because process plugins need to be able to write to the file system in order to initialize themselves and then run as a process. Perhaps the code could be reorganized to support this for only Wasm plugins... is there a real need for this feature?

**Comment by joscha** [comment]
> is there a real need for this feature?

it does mean I can't use NixOS testing facility to test the plugins. How about allowing to define the path that is used to write the cache to? Something like `PLUGIN_CACHE_DIR=...` or so? That would also solve #376 quite nicely actually, as I'd be able to produce a new cache path whenever the set of plugins changes.

**Comment by joscha** [comment]
Just ran clear-cache and saw this:
```
[nix-shell:~/work/nixpkgs]$ dprint clear-cache
Deleted /Users/joscha/Library/Caches/dprint/cache
```

which also shows me that the cache currently is not isolated either inside nix - passing a cache directory would fix this as well. Is that something we could do @dsherret?

**Comment by joscha** [comment]
And one more:

I tried running `clear-cache` as part of the nix installation, but was presented with this (unsurprisingly):

```
Error creating cache directory: Error("Error creating directory /homeless-shelter/Library/Caches/dprint/cache: Read-only file system (os error 30)")
```

**Comment by dsherret** [comment]
I added `DPRINT_CACHE_DIR` https://github.com/dprint/dprint/commit/1b9192d6adcd30be28d4528df0e915ce6705e0d7

I haven't done a new release for all these changes yet though. Let me know if you would like one (I'd like to sort out all these issues first).

**Comment by joscha** [comment]
Ah that's great! Let me test it out first and come back to you!

**Comment by joscha** [comment]
@dsherret the feature works well! I did notice that in some cases I get a `No such file or directory` seemingly *before* I see `[VERBOSE]: Creating directory:` - will hunt for a bit to see if I can find a place where the cache directory is accessed before we log an attempted access. I can only see this on our Ubunut-based CI, so I have the feeling that maybe the directory permissions are wrong in some cases and dprint tries to access it before logging.

**Comment by joscha** [comment]
> will hunt for a bit

couldn't find anything. `Path.display` shouldn't do any access. 🤷
