### ISSUE TITLE
CLI flag to disable cache

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#376]
Right now dprint plugins are downloaded, compiled, and cached if remote or compiled and cached if local. It might be useful to have a CLI flag (ex. `--disable-plugin-cache`) for some users to bypass this as pointed out in #374.

cc @joscha

**Comment by dsherret** [comment]
I'm not sure it's worth it to implement this feature either because process plugins need the cache in order to initialize themselves so they can run. I would like to understand the use case in #374 more before implementing this. I think there is probably just a bug in the caching mechanism. I'll reopen this if necessary in the future.

**Comment by joscha** [comment]
> I think a workaround is to call `dprint clear-cache` before calling a command that relies on the cache.

I only want to do this if the plugins have changed, right? Otherwise performance will be impaired I believe?

So basically what currently happens is that if I change the plugins that are passed via `--plugin`, I sometimes get this error. If I don't want to call this before every invocation, when do you suggest for me to call it? Is there a way for me to find out when the cache is stale? Or alternatively, could `clear-cache` take a `--plugin` parameter into account and only clear stale entries?

**Comment by dsherret** [comment]
@joscha yes, you would have a minor performance decrease because it will need to recompile the plugins. If you provide me with an example so that I'm able to reproduce what's going on in #374 then I don't believe you will need to clear the cache. I believe it should be able to figure it out on its own and know when to invalidate itself.

**Comment by joscha** [comment]
Got it. Will try to produce a standalone repro. Will I still see the error printed by default on CLI after your change or do I need to enable logging somehow first?

**Comment by dsherret** [comment]
Hmmm… I guess actually since the warning doesn’t surface anymore in the main branch it might not be that big of a deal and you shouldn’t bother having to clear the cache (by the way, make sure the folder isn’t important that you set for the cache dir because it will delete itself). You would see the old messages with the ‘--verbose` flag, but it’s a little noisy. I just think if you’re having to manually clear the cache when the file path changes or if it outputs the previous messages under verbose then there’s room for improvement with the cache. Not a big deal if you can’t figure out a reproduction though… as long as it’s working without having to clear the cache!
