### ISSUE TITLE
Globbing is slow for large monorepo

### ISSUE THREAD

**Issue by ryan-rushton** [dprint/dprint#379]
Version: 0.15.1

We have a large monorepo and are trying to run some fast formatting commands on single files. Globbing is causing issues as it takes 4-6 seconds as part of the format for a single file.

```
dprint fmt --verbose --config ~/work/some-org/dprint.json ~/work/some-org/web/src/blah.json
[VERBOSE]: Creating directory: /Users/ryanrushton/Library/Caches/dprint/cache
[VERBOSE]: Reading file: /Users/ryanrushton/Library/Caches/dprint/cache/cache-manifest.json
[VERBOSE]: Reading file: /Users/ryanrushton/Library/Caches/dprint/cache/plugin-cache-manifest.json
[VERBOSE]: Reading file: /Users/ryanrushton/work/some-org/dprint.json
[VERBOSE]: Reading file: /Users/ryanrushton/Library/Caches/dprint/cache/plugins/dprint-plugin-json/dprint-plugin-json-0.12.3.cached
[VERBOSE]: Reading file: /Users/ryanrushton/Library/Caches/dprint/cache/plugins/dprint-plugin-markdown/dprint-plugin-markdown-0.9.4.cached
[VERBOSE]: Globbing: ["!**/node_modules", "!**/*-lock.json"]
[VERBOSE]: File(s) matched: []
[VERBOSE]: Finished globbing in 4331ms
[VERBOSE]: Writing file: /Users/ryanrushton/Library/Caches/dprint/cache/cache-manifest.json
[VERBOSE]: Reading file: /Users/ryanrushton/Library/Caches/dprint/cache/some-org.incremental
[VERBOSE]: Checking path exists: /Users/ryanrushton/Library/Caches/dprint/cache/some-org.incremental
[VERBOSE]: Creating instance of dprint-plugin-json
[VERBOSE]: Created instance of dprint-plugin-json in 1ms
[VERBOSE]: Reading file: /Users/ryanrushton/work/some-org/web/src/ui/home/search/search_bar/blah.json
[VERBOSE]: Formatted file: /Users/ryanrushton/work/some-org/web/src/ui/home/search/search_bar/blah.json in 0ms
[VERBOSE]: Writing file: /Users/ryanrushton/work/some-org/web/src/ui/home/search/search_bar/blah.json
Formatted 1 file.
[VERBOSE]: Writing file: /Users/ryanrushton/Library/Caches/dprint/cache/some-org.incremental
```

Note the `[VERBOSE]: Finished globbing in 4331ms`

Is there some way we can work around this? We are trying to build tooling for our IDE's to run dprint on save for a single file.

When running in smaller test repo's this is a non issue but the length that this takes causes issues with the IDE and is not great for developer productivity.

Happy to help diagnose the issue we are just not sure where to start.

**Comment by ryan-rushton** [comment]
For reference, while it is done in code our tooling is effectively trying to replicate this
```
cat ~/work/some-org/web/src/blah.json |  dprint fmt --config ~/work/some-org/dprint.json --stdin ~/work/some-org/web/src/blah.json
```

**Comment by declanvong** [comment]
I have a PR for this that I'll raise later this week. It resolves the globbing speed issue in the editor service, which is probably the 99% case where you care about speed and responsiveness.

**Comment by dsherret** [comment]
@ryan-rushton wow, that is slow. It's weird that it's globbing that when a single file is specified... I forget how it's implemented.

> We are trying to build tooling for our IDE's to run dprint on save for a single file.

Have you seen https://github.com/dprint/dprint/blob/main/docs/editor-extension-development.md ? Also, yeah you should be using `--stdin` with an editor if you don't want to use the "editor-service", but perhaps that has this same problem.

> I have a PR for this that I'll raise later this week. It resolves the globbing speed issue in the editor service, which is probably the 99% case where you care about speed and responsiveness.

@declanvong great to know!

**Comment by ryan-rushton** [comment]
I missed the editor service. I will port over to that and see if I see an improvement. I don't think it's 100% necessary for my use case as I am doing all this in another thread to not block the UI. If it fixes my issue though I will happily use it.

**Comment by ryan-rushton** [comment]
@dsherret one other think I noticed is that you don't get verbose logs when using the `--stdin` option. Is this expected or a bug? I used the non-stdin to get those results but overall I am seeing the same timeframes so I assume they are related.

**Comment by dsherret** [comment]
Also, I just looked at the code for the editor-service and I think it has this problem as well. There's definitely some optimizations that could be done here.

**Comment by dsherret** [comment]
I don't think #380 entirely solves this, but does make things faster for the editor service. Reopening.

**Comment by dsherret** [comment]
This is released now and both the editor servive and `dprint fmt --stdin` should be much faster.
