### ISSUE TITLE
segmenting format/check runs

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#381]
Hi,

we have a large repository with many folders. We want to enforce formatting on CI but keep some folders logically grouped together in disjoint formatting runs. Think of:

```
folderA
folderB
folderC
...
```

where we want to:
* enforce formatting on `folderC`
* enforce formatting on `folderA` and `folderB`
* enforce formatting on anything but `folderX, folderY and folderZ`

in separate CI runs, which basically needs disjoint formatting/check runs for each folder (combination).

Ideally I'd be able to dynamically decide the composition of these groups that I format/check together.
But even statically defined groups would be good, however the issue currently is that:
* there is no easy way to create multiple config files that extend each other as `includes` and `excludes` are not inherited
* there is no way to pass a glob to the checker/formatter, e.g.: `dprint output-file-paths -- 'folderC/**'` yields an empty list
* there is no way to pass `--excludes` without overriding the `excludes` coming from the config file
* there is option to pass `--includes` at all, but if there were it would probably also overwrite the `includes` from the config, and we have negative globs in the `includes` array.

Ideas:
* Allow inheritance of `includes` and `excludes` across config files or via CLI (I read somewhere in the docs there is a security issue of some sort why this is not done, is there more info?)
* Allow passing globs to the file list
* Allow passing a stream of files via stdin to dprint (then I can run the globs myself or run `output-file-paths` and filter the list down based on my groups); this is not my favorite solution is it is much slower and requires maintaining extra code to make this happen, but I take it if that is the only acceptable option
* Allow passing a config via stdin that I can generate in memory (then I can dynamically extend `includes`/`excludes`); I can do this with a temporary file and then pass it via `--config`. This feels clunky, but I will do this if none of the other options are acceptable.
* formatting everything, `git checkout`ing the parts that are not in the folders I am interested in and use `git diff --exit-code ^HEAD` to assert up-to-date formatting. Not my favorite option either as it formats too many things which wastes a lot of time of the segment I want to format is much smaller than the whole.
* Your idea here :)

Thoughts? Thanks so much!

**Comment by joscha** [comment]
Just saw on `fmt`:
```
<files>...    List of file patterns in quotes to format. This overrides what is specified in the config file.
```

which suggests `fmt` supports passing something like `--includes`, however overriding the `includes`.

I am currently looking at compiling a subset of list of files to pass to dprint, but noticed that dprint does not support reading a list of files from stdin. Passing them as arguments means it will most likely exceed the standard argument length.

Idea: support reading a list of files from stdin, something like:

```bash
cat list_of_files.txt | dprint fmt -- -
```

or similar?

**Comment by dsherret** [comment]
Sorry, I missed this. I will look into it soon... just tired after today now 😅

**Comment by joscha** [comment]
No worries. I decided to go with a dynamically generated config for now,
but it's not ideal. Anything else didn't work as having a plugin
configuration in the JSON throws an error if the respective plugin is not
loaded. Would be great to have a chat. Also happy to Skype/zoom/hangout to
explain more.

**Comment by joscha** [comment]
Still working on this. My idea was to segment by plugin, however there is a problem with that as well:

* dprint assumes that a plugin that is loaded is always used, e.g. if you run `dprint --plugin a` it will run plugin `a`, whether you like it or not and whether there is a config for it or not. Ideally I'd be able to pass an arbitrary number of plugins and then the config file defines whether they are enabled or not.
* a configuration for an unknown plugin in the config file throws an error. E.g. there is no way for me to define `{ pluginA: {}, pluginB: {}}` and then run `dprint --plugin pluginA`, and only run `pluginA`, as it will complain about the existence of the configuration for `pluginB`.


Ideally either:
* superfluous configuration (e.g. configuration for a plugin that is not there) is ignored instead of erroring (maybe we can introduce a `required: boolean` flag or something to fail it and make it true by default, so that change is backwards compatible. That way I can run dprint with a subset of plugins, only reading the config I need but ignoring others.
* or allow to drive via configuration which plugins are executed, independently of which are loaded (e.g. `dprint --plugin a --plugin b` with a config of `{ a: {...}}` would only execute `a` and ignore the existence of `b`

**Comment by dsherret** [comment]
@joscha I think #387 might solve the first two points you mentioned in the original post.

I just wanted to do this myself when slowly converting a project and it formatted everything, which I didn't want to happen. This will allow you to do:

```bash
(cd folderA && dprint fmt)
(cd folderB && dprint fmt)
```

I think this would solve your use case? Seems like there's some additional changes that should be made though anyways.

**Comment by joscha** [comment]
Hey David, I think generally that would probably work. I had to move away from folders as we have a heterogeneous monorepo where different file types are under the same subpath. So in addition to restricting the files that are formatted i also need to run the types that are formatted (e.g. the plugin).
I'll write a follow up comment here to explain how I do it, but basically what u do right now is i control which plugins I pass to dprint via `--plugins` and then I generate a temporary dprint config with the right `extends` content in a temp folder. That is not ideal as it still globs more than needed (if I wanted to solve that I need to dynamically write a unified dprint.json which merges includes/excludes) but it allows me to run formatting segmented by plugin for the whole repo. And segmented by plugin for a set of files via ` -- fileA fileB fileC` the only issue I see there is that there is a maximum limit for passing the file list via CLI, to solve that I'd need to teach dprint to take the lost of files via stdin (maybe via `cat list | dprint fmt -- -`).

**Comment by dsherret** [comment]
> superfluous configuration (e.g. configuration for a plugin that is not there) is ignored instead of erroring (maybe we can introduce a required: boolean flag or something to fail it and make it true by default, so that change is backwards compatible. That way I can run dprint with a subset of plugins, only reading the config I need but ignoring others.

I've changed it in https://github.com/dprint/dprint/commit/f33209b9192ba984d125f7a08a16731eddb0145a to not error when `--plugins` is provided as a CLI argument. That at least solves that problem, but I still need to read and tackle a few other points in here.

**Comment by joscha** [comment]
This is great, will try it asap!

**Comment by joscha** [comment]
We're having a bit of trouble rebasing our fork due to 1cca28d1365a30e1593f28d0fd4c11f3b13c5ac0 and 68507fc007629b415f4e226c4a3371c2edaa9d2e 😬 but I haven't forgotten about this. Will most likely happen tomorrow (AEST).
