### ISSUE TITLE
`output-resolved-config` does not return valid JSON

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#383]
I am trying to parse the output of `output-resolved-config`, however the output is something like:

```
json: {
  "array.preferSingleLine": false,
  "commentLine.forceSpaceAfterSlashes": true,
  "ignoreNodeCommentText": "dprint-ignore",
  "indentWidth": 2,
  "lineWidth": 120,
  "newLineKind": "lf",
  "object.preferSingleLine": false,
  "useTabs": false
}
markdown: {
  "emphasisKind": "underscores",
  "ignoreDirective": "dprint-ignore",
  "ignoreEndDirective": "dprint-ignore-end",
  "ignoreFileDirective": "dprint-ignore-file",
  "ignoreStartDirective": "dprint-ignore-start",
  "lineWidth": 80,
  "newLineKind": "lf",
  "strongKind": "asterisks",
  "textWrap": "maintain"
}
```

is there any chance we could evolve this into valid JSON? E.g. add wrapping `{}`, quotes of the keys and commas between the sections. I can add the wrapping manually in my parser for now, but I think this is quite unexpected.

**Comment by uri-canva** [comment]
That's valid YAML (then again YAML is almost like perl in that almost anything is valid YAML).

**Comment by joscha** [comment]
Haha, fair. Let me try to parse it as yaml first.

**Comment by dsherret** [comment]
It wasn't intended to be parseable and the output was just a very fast initial implementation.

That said, I think it would probably be ok for it to output as JSON instead. I was wondering if there should be a `--json` flag or something, but I think that's unnecessary. The command was intended to be for debugging so it can serve dual purpose.

**Comment by joscha** [comment]
Works a charm. Sorry for the noise.

**Comment by dsherret** [comment]
@joscha see my last comment. It's just a coincidence that it's yaml 😅. I'm going to reopen as there's no guarantee this will happen to parse as yaml in the future.

**Comment by joscha** [comment]
Haha, fair. I think if we can make it parseable I'd prefer JSON over yaml, but that's because it means I need less dependencies to parse it. Either is fine. I can see if I can make the change.

**Comment by dsherret** [comment]
Definitely JSON as it's used elsewhere in the CLI. That would be great, thanks!

**Comment by dsherret** [comment]
Oops... I forgot you mentioned you would take a look into this one, but anyway it was a small change so I quickly did it just now. Will be in v0.16

**Comment by joscha** [comment]
No worries! Appreciated! Would have been a good chance to learn some Rust :) next time!
