### ISSUE TITLE
feature request: global config file

### ISSUE THREAD

**Issue by insomnimus** [dprint/dprint#385]
Please support a global config file.

Running `dprint init` is fine, however it always initializes with the defaults  
and I always end up configuring it.

I know i can pass the config file from the command line but a default one is many times better  
than specifying it through the command line each time.

I also tried adding `.dprint.json` at the root of my development directory
but this doesn't work well because everything under the root directory gets formatted.

Another way of accomplishing this would be if dprint supported extensions like cargo.  
For example some `dprint-custominit` in `$PATH`, where I myself  
could write the executable.

**Comment by dsherret** [comment]
Duplicates #355. Thanks for your comment and I've updated that issue with it 🙂
