### ISSUE TITLE
show `check`-like diff when doing `fmt`

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#388]
is there any way to also save the diff that one gets when doing a `check` run when running `fmt`? I am trying to run `dprint fmt` but still getting the nice diff that dprint spits out on `check`. I am currently experimenting with `git diff HEAD --color --color-words --ws-error-highlight=all` but it's nowhere near as good. Another alternative would be to use https://github.com/so-fancy/diff-so-fancy or similar or run dprint twice (once in `check` mode and once in `fmt`, however that seems excessive).

**Comment by dsherret** [comment]
This will be `dprint fmt --diff` in 0.19.
