### ISSUE TITLE
Map custom file extension to specific formatter

### ISSUE THREAD

**Issue by DrSensor** [dprint/dprint#392]
Some bundlers like [parcel](https://v2.parceljs.org/configuration/plugin-configuration) use RC file (`.parcelrc`) for their config instead of `parcel.json`. Maybe support a field like `"filetypes"` in the dprint.json to specify which formatter should be used for specific filenames/extensions.

```json
{
  "filetypes": {
    ".*rc": "json",
    "tsconfig.json": "jsonc"
  }
}
```
inspired from [esbuild](https://esbuild.github.io/api/#loader)

**Comment by dsherret** [comment]
This is released now in 0.19.0. Read more here: https://dprint.dev/config/#associations
