### ISSUE TITLE
Globbing broken (`excludes`) in 0.16.1

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#401]
Version: `0.16.1`

We have an excludes rule in the config in `0.15.0`:
```json
  "excludes": [
    "report.*.*.*.*.*.json"
  ]
```

that excludes some JSON that is created by IntelliJ:
```bash
.ijwb/report.20201030.234629.86995.0.001.json
.ijwb/report.20210827.130047.13633.0.001.json
.ijwb/report.20201030.235004.87316.0.001.json
.ijwb/report.20210827.132614.16001.0.001.json
# more here
````
Before, these files were ignored, with `0.16.1` they are now a match, being part of `output-file-paths` or `check`:

```
dprint output-file-paths --plugins https://plugins.dprint.dev/json-0.12.0.wasm https://plugins.dprint.dev/markdown-0.8.0.wasm
```

I thought it was maybe introduced in a825704706bb94a6b60a88dbd951f41f4d092552 and fixed again in bde47767604f71c6e129242191a6040226b5e730 but it seems to persist on `HEAD` (d78651ba4bf0cfc29e86d522da48b422186c3002). Will try and create a unit test for it.

**Comment by dsherret** [comment]
Will fix it tomorrow.

**Comment by joscha** [comment]
> Will fix it tomorrow and do a new release.

Would you like me to prep a unit test you can assert against?

**Comment by dsherret** [comment]
Sure! That would be great.

I think a problem at the moment is that the `Environment` does globbing, but I think instead it should only do directory walking. Then I could implement globbing at a higher level to test it properly with a `TestEnvironment`. I'll try to do that tomorrow too.

**Comment by joscha** [comment]
> Sure! That would be great.

👍  Will do my best.

> I think a problem at the moment is that the `Environment` does globbing, but I think instead it should only do directory walking.

yeah maybe. The extglob rules that git (and dprint) support are super complex anyway and there are lots of edge cases that can only be answered with access to the file system (for example the glob above is defined in the root, but applies to all folders but it doesn't have a slash, so only to files).

Aside: this issue is also indirectly related to #378

**Comment by joscha** [comment]
You're probably coming online soon :) I haven't found a good spot for the test, it seems the globbing parts are untested for the most part?

I am think about adding a new set of tests to: https://github.com/dprint/dprint/blob/bde47767604f71c6e129242191a6040226b5e730/crates/dprint/src/cli/patterns.rs ? Is that the right spot?

**Comment by dsherret** [comment]
@joscha sorry, missed this (accidentally slept in a bit this morning then was in a rush).

Don't worry about it! I'm going to submit a couple PRs right now that makes this better tested.

**Comment by dsherret** [comment]
@joscha I investigated this and realized this working as intended because it's in a sub directory. This will be the behaviour going forward (sorry for such a breaking change, but the CLI has not stabilized yet. I also did know it used to work this way... must have "fixed" it when I made the change to use absolute globs).

Basically, that will only ignore files in the same directory as that config file. So to make it ignore descendant directories change the glob to have a leading `**/`:

```json
"excludes": [
  "**/report.*.*.*.*.*.json"
]
```

**Comment by joscha** [comment]
hmm, that is very different from the git behaviour that was respected until 0.16?

The documentation even says:

![Configuration_-_dprint_-_Code_Formatter](https://user-images.githubusercontent.com/188038/131420412-f41c1a36-917c-4cab-b58b-5fa7708ce5d0.png)

Via: https://git-scm.com/docs/gitignore#_pattern_format

especially:

> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.


The `Otherwise the pattern may also match at any level below the .gitignore level.` is what would have caught this before.

**Comment by dsherret** [comment]
Thanks! Will fix it to match 😄

**Comment by joscha** [comment]
We have code that transforms a tree of `.gitignore` and `.gitattributes` files into a `dprint.json`. It is possible to change all our globs, but transforming gitignore extglob syntax to standard globbing is mildly hard (I tried and failed to embed all the edge cases that rely on file access; basically to transform extglob to standard glob you need to not only walk the file system, but also reimplement the git implementation to a tee, which is quite tricky as it depends on the git version and there is no library that fully implements these). I do understand you wanting to support standard globbing syntax only (although we should probably clearly define the dialect/library used) - a simpler alternative that I could see as a way going forward is to make this breaking change, but add a new flag for #378 that reads `.gitignore` and `linguist-generated` and `linguist-vendored` whilst it is walking. The effective complexity would be the same, but it would be more clearly defined on what the intended behaviour is (and it would also solve the `includes`/`excludes` inheritance from #381 to an extent). Thoughts?

**Comment by joscha** [comment]
More thoughts:

* maybe we can piggyback on https://git-scm.com/docs/git-check-ignore somehow?
* can we introduce `.dprintignored` files in each dir level that stack? Then we could embed the formatting rules into those and not rely on gitignore logic at all. Basically for a `.gitignore` with `report.*.*.*.*.*.json` we'd have a `.dprintignore` with `**/report.*.*.*.*.*.json`. It would be slightly more verbose, but also have the advantage that we can control formatting and git ignore independently and it also solves the includes/excludes override problem nicely. Additionally it follows the the same pattern as other linters.

**Comment by joscha** [comment]
I am happy to brainstorm together via zoom/hangouts/skype and/or show you the generator that I wrote and how it works if you need a bit more rubber ducking support :)

**Comment by joscha** [comment]
> Will discuss that sometime in #378.

👍 

> No, wouldn't want to introduce another file.

too bad :) I think it would solve the problem nicely whilst at the same time remove contention in the global config file, keep excludes separate and also close to the code they are excluding (e.g. if I remove the folder, the exclusion rule is removed with it, with a global file this lingers and might never be removed).


> It would be good to meet sometime so I can walk through the challenges you're still having. Maybe send me an email and we can book a time 🙂

That would be great, will send you an email.
