### ISSUE TITLE
Investigate includes/excludes inheritance for non-remote config files

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#406]
As title.

**Comment by Avasam** [comment]
I have a question concerning excludes, what's the security risk? For includes https://github.com/dprint/dprint/issues/230 lays it out pretty clearly.
From what I can tell, the worst that can happen is that some files don't get formatted if the extended config is too aggressive and the current config doesn't itself specify excludes.

It'd be useful for a shared, cross-projects, global config file to be able to add commonly found to-be-excluded folders, for example:
```jsonc
{
  "extends": "https://raw.githubusercontent.com/Samuel-Therrien-Beslogic/beslogic-dprint-configuration/main/dprint.json",
  "includes": ["**/*.*"],
  "excludes": [ // I wouldn't have to add "excludes" to all my projects
    "**/node_modules",
    "**/*-lock.json",
    "**/coverage", // created on install by nx
    "**/build",
    "**/cache",
    "**/dist",
    "**/tmp",
    "**/obj"
  ]
}

```

**Comment by dsherret** [comment]
Sounds reasonable for excludes.
