### ISSUE TITLE
Improve globbing performance

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#407]
As noted in @joscha's message [here](https://github.com/dprint/dprint/pull/405#issuecomment-908840165) the globbing performance has degraded between v0.15.1 and v0.16.2. In that scenario it went from 10s to 25s on a repo with 30K matches.

There are definitely ways to make this faster again and maybe even moreso than before.

**Comment by dsherret** [comment]
I looked into this and have a solution that moves all the `fs::read_dir` calls to a separate thread. That seems to basically make globbing as fast as the total time of the read_dir calls. I’ll put up a PR in the next few days.

**Comment by joscha** [comment]
Nice! Can we abstract that part so dprint could support globbing plugins in
the future? ;-) ;-)

**Comment by dsherret** [comment]
@joscha I’ve thought about it, but I can’t think of a way that it would be fast and it probably introduces too much complexity.

**Comment by joscha** [comment]
OK. What about an acceptor callback that one can provide? E.g. a function passed to filter to reduce the list as we go. That way the ignore rules could be dynamic.

**Comment by dsherret** [comment]
On my C drive:

```ts
C:\
> Measure-Command { bvm exec dprint 0.17.0 output-file-paths } | Select-Object -Property TotalSeconds

TotalSeconds
------------
  19.0478789

C:\
> Measure-Command { bvm exec dprint 0.17.1 output-file-paths } | Select-Object -Property TotalSeconds

TotalSeconds
------------
  16.1716428
```

> OK. What about an acceptor callback that one can provide? E.g. a function passed to filter to reduce the list as we go. That way the ignore rules could be dynamic.

I'm not sure how this could be performant and it's difficult to do in Rust. I will just work on improving this to support .gitignore files.

**Comment by joscha** [comment]
> I'm not sure how this could be performant and it's difficult to do in Rust. I will just work on improving this to support .gitignore files.

no worries! Was just an idea :)
