### ISSUE TITLE
`--plugins` arg and file inputs clash

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#408]
Version: 0.16.1

The `dprint --help` text says:
```
    Search for files using the specified file patterns:

      dprint fmt "**/*.{ts,tsx,js,jsx,json}"
```

and then in `dprint fmt --help` it says:

```
dprint fmt [FLAGS] [OPTIONS] [--] [files]...
```

However combining the `--plugins` option with `[files...]`

via:
```
dprint fmt --plugins https://plugins.dprint.dev/typescript-0.48.0.wasm foo
```

yields:

```
The plugin '/Users/joscha/foo' must have a checksum specified for security reasons since it is not a Wasm plugin. You may specify one by writing "/Users/joscha/foo@checksum-goes-here" when providing the url in the configuration file. Check the plugin's release notes for what the checksum is or calculate it yourself if you trust the source (it's SHA-256).
```

because it can't discern when the plugins list ends and the file list begins.

Should we:

- always require `--`
- change the API for `--plugins` to `dprint fmt --plugins=A --plugins=B C`, so we can always discern that C is a glob/file in this case?
- treat a paramter that can't be loaded as plugin as a file input (this is not ideal as broken plugins will be treated as file inputs)

cc @wearymonkey

**Comment by dsherret** [comment]
I don't think this should require a design change. When using `--plugins` with file paths, just make sure to use two dashes before the files:

```ts
dprint fmt --plugins https://plugins.dprint.dev/typescript-0.62.0.wasm https://plugins.dprint.dev/json-0.14.0.wasm -- file.ts
```

I have added a message that should be helpful for people who run in this scenario:

```
> ./target/debug/dprint fmt --plugins https://plugins.dprint.dev/test.wasm other.ts
other.ts was specified as a plugin, but it doesn't look like one. Plugins must have a .wasm or .exe-plugin extension.

Maybe you meant to add two dashes after the plugins?
  --plugins https://plugins.dprint.dev/test.wasm -- other.ts [etc...]
```
