### ISSUE TITLE
Add dprint-plugin-exec for formatting files based on a shell command

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#411]
This would be a plugin that allows you to specify any CLI tool for formatting with dprint's CLI and editor extensions. The CLI tool would need to exist on the system for it to work. For example, a configuration file might look like the following and require #365 to be implemented:

```jsonc
{
  "incremental": true,
  "exec": {
    "associations": "**/*.{rs,js}", // special property introduced in #365
    "cacheKey": 1, // bump to force the incremental cache to be re-evaluated. Useful when underlying tool is upgraded
    "rustfmt": "rustfmt", // command that accepts a file text via stdin
    "rustfmt.associations": "**/*.rs",
    "prettier": "prettier --stdin-filepath $file_path" // all other files would go here
  },
  "includes": [
    "**/*.{rs,js}"
  ],
  "plugins": {
    "https://plugins.dprint.dev/exec-0.1.0.exe-plugin@checksum-goes-here"
  }
}
```

Helper variables: `$file_path` and `$file_text`. Providing `$file_text` makes it not pipe in the file text via stdin.

Anyway, the details of this could be worked on entirely in that plugin and be completely separate from the CLI. I'm storing this idea in here for now though. I think it would be very useful because people could then make many other formatting tools work easily with dprint.

**Comment by joscha** [comment]
I think this could be really strong to drive adoption. What are your thoughts about execution overhead of the external execution? That the plugin would pass the glob to the external tool in some way? If yes, how would we produce the diff on a `check`? Would we expect the CLI to format in memory and return a huge diff? Or that there is some sort of resident management in the plugin wrapper that allows keeping a process warm to pass each file to?

**Comment by azherebtsov** [comment]
Hey @dsherret !

Plugin code is ready, I think we need a repo for it.

**Comment by dsherret** [comment]
@azherebtsov amazing! I added you as a collaborator on https://github.com/dprint/dprint-plugin-exec

**Comment by joscha** [comment]
Awesome!

@azherebtsov let's pick this up in February - or if you want to go ahead before then you can talk to @ryan-rushton about the process to get this started, there are a couple of things to be done beforehand.

**Comment by dsherret** [comment]
@azherebtsov sorry, I get too much GH notifications nowadays and missed this.

> Have a question: are you "ok" to take ownership and maintenance of the future exec plugin code? Basically we will donate the code to you and will be contributing as any other public contributor.

Yes, for sure! Thank you so much!

**Comment by dsherret** [comment]
This is now released (https://github.com/dprint/dprint-plugin-exec) and supports formatting with multiple CLI commands. Thanks a lot to @azherebtsov for the initial implementation 🙂

**Comment by dsherret** [comment]
Example use in Deno: https://github.com/denoland/deno/pull/13735

**Comment by azherebtsov** [comment]
> This is now released (https://github.com/dprint/dprint-plugin-exec) and supports formatting with multiple CLI commands. Thanks a lot to @azherebtsov for the initial implementation 🙂

Thank you @dsherret ! New features in `0.1.1` are simply amazing. I already opened a PR in our private repo to merge them ...
