### ISSUE TITLE
globbing: wildcardless glob that doesn't match anything errors

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#415]
Version: 0.17.1

`includes` expect glob patterns, theoretically any string is a valid glob pattern even if it doesn't contain a wildcard.

A configuration like this:

```json
{
  "$schema": "https://dprint.dev/schemas/v0.json",
  "typescript": {
  },
  "includes": [
    "**/*.ts",
    "a/wildcardless/glob/that/can/potentially/match/a/single/file.ts"
  ],
  "excludes": [
    "**/node_modules"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.55.0.wasm"
  ]
}
```

yields an error:

```shell
❯ dprint fmt
Error formatting /Users/joscha/test/a/wildcardless/glob/that/can/potentially/match/a/single/file.ts. Message: Error reading file /Users/joscha/test/a/wildcardless/glob/that/can/potentially/match/a/single/file.ts: No such file or directory (os error 2)
Had 1 error(s) formatting.
```

More background:
----

We encounter this with a shared repository-wide `dprint.json` and sparse checkouts, e.g. some files that are referenced in the includes may not be there, but we don't actually care that they are not.

The reason we have these includes definition in the first place are patterns like:

```gitattributes
*/**/*_generated.ts linguist-generated=true
path/to/some_special_file_generated.ts linguist-generated=false
```

where we have chunks of the repository marked as generated and then exclusions nested. Whilst generated files are passed to the `excludes`, these nested overrides need to be added to the `includes`.

cc @declanvong

**Comment by dsherret** [comment]
This is actually currently expected behaviour. I'd prefer to let the user know about this in some way because if someone misspells a filename then they will get feedback right away about this. I think I will change it to instead log to stderr when it can't find the file.

**Comment by joscha** [comment]
You wouldn't ever log if there was a wildcard in it though or would you?
I guess the question is whether the includes are globs only or a mix of globs and filenames. In the second case I'd expect it to log as well I suppose.

**Comment by dsherret** [comment]
No, it would only do this just for patterns that are essentially like file paths.

**Comment by joscha** [comment]
Yes, so my point is, if it's all globs I am not sure if it should ever
error, because non-matches for other globs with wildcards wouldn't ever
error either?

**Comment by dsherret** [comment]
It's not going to error, but it will log to stderr as a warning (without failing like it currently does). Basically if someone has essentially a file path in their config that doesn't match any file it will warn. The reason is to alert someone to when they might have made a mistake and mistyped a file path.

**Comment by joscha** [comment]
Okay. I feel like non-matches are a feature and it's currently a bit confusing with sparse checkouts but I can follow your reasoning for the standard case. We can possibly adapt the fixed file paths with a globbing addition. Something like `.?` at the end, so dprint interprets it as a glob and never warns.

**Comment by dsherret** [comment]
Ok, thinking about it more, maybe it does cause more trouble than it’s worth.
