### ISSUE TITLE
Regression: globbing ignores trump later includes regardless of order

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#416]
Version: 0.17.1 but probably (untested) 0.16.0 and newer

Behaviour:
```json
{
  "$schema": "https://dprint.dev/schemas/v0.json",
  "json": {
  },
  "includes": [
    "!**/*.{json}",
    "**/a.json"
  ],
  "plugins": [
    "https://plugins.dprint.dev/json-0.13.0.wasm"
  ]
}
```

with a folder like:
```
-rw-r--r--   1 joscha  staff     0 21 Sep 12:47 a.json
-rw-r--r--   1 joscha  staff     0 21 Sep 12:47 b.json
-rw-r--r--   1 joscha  staff   198 21 Sep 12:52 dprint.json
```

yields an empty list with `output-file-paths`:

```
dprint --version
dprint 0.17.1

dprint output-file-paths
```

with `0.15.1` this correctly prints `a.json`:
```
❯ /Users/joscha/Downloads/dprint --version
dprint 0.15.1

❯ /Users/joscha/Downloads/dprint output-file-paths
/Users/joscha/work/dprint-glob-test/a.json
```

We use the original behaviour for opting out whole subtrees and then slowly opting, in, think of:

```glob
// format all JSON
**/*.json
// opt-out folder x
!x/**/*.json
// but format all in x/y
x/y/**/*.json
```

Please note that this regression has no workaround that I could find as of this moment. The glob order does not seem to matter whatsoever, ignores seem to always trump regardless of their position.

**Comment by dsherret** [comment]
Interesting. I didn't know it behaved this way, but that makes sense to do. I'll mark it as a bug and do a patch release now.

**Comment by joscha** [comment]
> I'll mark it as a bug and do a patch release now.

awesome! Thanks so much!

**Comment by joscha** [comment]
I think the `0.17.2` behaviour is not 100% sane anymore now:

for:
```
-rw-r--r--   1 joscha  staff     0 21 Sep 12:47 a.json
-rw-r--r--   1 joscha  staff     0 21 Sep 12:47 b.json
-rw-r--r--   1 joscha  staff   215 22 Sep 12:11 dprint.json
```
with:
```jsonc
{
  "$schema": "https://dprint.dev/schemas/v0.json",
  "json": {
  },
  "includes": [
    // opt in all JSON
    "**/*.json",
    // opt-out all JSON
    "!**/*.json",
    // opt-in only a.json
    "a.json"
  ],
  "plugins": [
    "https://plugins.dprint.dev/json-0.13.0.wasm"
  ]
}
```

```shell
> dprint --version
dprint 0.17.2

> dprint output-file-paths
```

yields:
```
/Users/joscha/work/dprint-glob-test/a.json
/Users/joscha/work/dprint-glob-test/dprint.json
/Users/joscha/work/dprint-glob-test/b.json
```
instead
```
/Users/joscha/work/dprint-glob-test/a.json
```

**Comment by dsherret** [comment]
Hmmm... apart from some pre-processing, it's essentially directly using globset now.

```rs
use globset::GlobBuilder;
use globset::GlobSetBuilder;

fn main() {
  let glob_set = GlobSetBuilder::new()
    .add(GlobBuilder::new("**/*.json").build().unwrap())
    .add(GlobBuilder::new("!**/*.json").build().unwrap())
    .add(GlobBuilder::new("a.json").build().unwrap())
    .build()
    .unwrap();

  println!("{}", glob_set.is_match("/test/a.json"));
  println!("{}", glob_set.is_match("/test/b.json"));
  println!("{}", glob_set.is_match("/test/c.json"));
}
```

And:

```rs
use globset::GlobBuilder;
use globset::GlobSetBuilder;

fn main() {
  let glob_set = GlobSetBuilder::new()
    .add(GlobBuilder::new("**/*.json").build().unwrap())
    .add(GlobBuilder::new("!a/**/*.json").build().unwrap())
    .add(GlobBuilder::new("a/b/**/*.json").build().unwrap())
    .build()
    .unwrap();

  println!("{}", glob_set.is_match("/a/a.json"));
  println!("{}", glob_set.is_match("/a/b/b.json"));
  println!("{}", glob_set.is_match("/dprint.json"));
}
```

Both output:

```rs
true
true
true
```

## `ignore` crate

After some investigation, it looks like I am using globset incorrectly, but ideally the code should be using the `ignore` crate as that's what globwalker is using (previous glob walking dependency). It outputs as expected. https://crates.io/crates/ignore

**Comment by joscha** [comment]
> println!("{}", glob_set.is_match("/a/a.json"));

this ine is incorrect, as only the `b` subdir has been opted in. I have produced a testcase but have trouble running it, I am getting:
```
error: couldn't read crates/dprint/src/../../../target/release/test-process-plugin: No such file or directory (os error 2)
```
when trying to run the tests. Seems like `cargo build` only produces `target/debug`.
Let me push the test case anyway, so we can look at it.

**Comment by dsherret** [comment]
Yeah, the output of using globset directly is not desired. I opened https://github.com/dprint/dprint/issues/417

**Comment by joscha** [comment]
Here is the test case: https://github.com/dprint/dprint/pull/418
