### ISSUE TITLE
NPM package should allow installing when using apple m1

### ISSUE THREAD

**Issue by jfrconley** [dprint/dprint#420]
Currently, the npm package will refuse to install on any architecture other than x64. However, rosetta allows dprint to run perfectly fine on m1 macs using arm64. The install script should allow for this case as it's an easy way to increase compatibility.

I could put up a PR for this if people are amenable to it.

**Comment by dsherret** [comment]
Yeah, that would be good to do. If you're up for it, that would be appreciated and the install script is here https://github.com/dprint/dprint/blob/main/deployment/npm/install.js -- If not, I will get to it soon.

I'm hoping in the future to have M1 builds, but I'm just waiting on GitHub actions to support it.

**Comment by dsherret** [comment]
I ended up looking into this because I'm doing a release right now for version 0.17.3 and wanted to get it in.
