### ISSUE TITLE
Plugin request: SQL formatter

### ISSUE THREAD

**Issue by thomaseizinger** [dprint/dprint#425]
I've found this: https://github.com/shssoichiro/sqlformat-rs

Might not be too hard to build a plugin on top of this! It seems like pure Rust code so should compile to WASM without issues :)

**Comment by dsherret** [comment]
Sure. Try it out: https://github.com/dprint/dprint-plugin-sql/releases/

**Comment by thomaseizinger** [comment]
I guess this can be closed then, thank you! :)
