### ISSUE TITLE
More specific error reporting when there is a panic in spec testing

### ISSUE THREAD

**Issue by IWANABETHATGUY** [dprint/dprint#444]
currently, when you encounter a runtime error in spec testing, the result shows below:
![image](https://user-images.githubusercontent.com/17974631/145720067-aaf8ed03-c25c-4e03-84e6-d68d82aee57e.png)
there is no way to know which spec file failed, this is anoying when you have multiple testing file, you need to check it one by one,
It's better to show which file failed testing

**Comment by dsherret** [comment]
What is src/parser/parser.rs? It looks like a panic in there.

What's the output when setting the environment variable `RUST_BACKTRACE=1`?

**Comment by IWANABETHATGUY** [comment]
```json
~~ array.preferSingleLine: true, lineWidth: 40 ~~
== should prefer collapsing the JSON array to a single line ==
{
  prop: [
    1,
    2
  ],
  "prop2": [
    "testing this out",
    "testing testing test"
  ]
}

[expect]
{
  "prop": [1, 2],
  "prop2": [
    "testing this out",
    "testing testing test"
  ]
}
```
It panic because my json parser is a standard parser , it can't parse object prop key without quoted.
current it just report the call stack, but it would be better to told the developer that which file and which case trigger the panic, 
for example:
```
panic due to xxx.txt::should prefer collapsing the JSON array to a single line
```

**Comment by dsherret** [comment]
Can you return a result instead of panicking in the parser? That would be more ideal.

**Comment by IWANABETHATGUY** [comment]
Alright, just want to investigate a better way to show more meaningful error message when the spec testing is failed.

**Comment by dsherret** [comment]
It was easy to do, so I added some code to unwind the panic and say what file the error occurred in. I recommend returning a `Result` though.
