### ISSUE TITLE
dprint-plugin-exec

### ISSUE THREAD

**Issue by azherebtsov** [dprint/dprint#448]
Hey @dsherret !

In Canva we developed `dprint-plugin-exec`.
It is a process plugin which can execute any CLI installed on the host. It support passing input to the CLI's `stdin` or as a file path via `args`, plugin configuration can be passed via args as well by using Handlebars template language. Our specific use case was to support Java files, but we know that there are formatters for other languages which are not handy to implement in Rust, such as for Kotlin, Bazel BUILD files etc... This could increase adoption of the `dprint` as a one-size-fits-all tool that manages formatting of multi-language projects.  

Please let me know if this is something you'd like to see in a standard set of plugins. We are looking into opportunities to open-source the code (this is WIP now). 

CC @joscha

**Comment by dsherret** [comment]
Hey @azherebtsov, that's great to hear canva developed that! Yes, it would be really good (see #411)

**Comment by azherebtsov** [comment]
Ah, sweet! So we can close this issue in favour of https://github.com/dprint/dprint/issues/411.
