### ISSUE TITLE
Download plugins by SOCKS proxy does not work

### ISSUE THREAD

**Issue by hustcer** [dprint/dprint#450]
Version: 0.20.0

```bash
Error resolving plugin https://plugins.dprint.dev/markdown-0.12.1.wasm: Error downloading https://plugins.dprint.dev/markdown-0.12.1.wasm - Error: "https://plugins.dprint.dev/markdown-0.12.1.wasm: Connection Failed: Connect error: SOCKS feature disabled."
```
If I remember correctly， download plugins by SOCKS proxy works before, any way to enable it? Or can I download the wasm file manually and place it somewhere to make `dprint` load it? Thanks

**Comment by dsherret** [comment]
@hustcer sorry about that! Try in 0.20.1. I didn't have the socks feature enabled on ureq.

**Comment by dsherret** [comment]
By the way, dprint supports downloading wasm plugins and loading them from your file system.

**Comment by hustcer** [comment]
@dsherret Great, SOCKS proxy works now. 

Where should I put the downloaded wasm plugins? Is there a doc about this? Thanks
> By the way, dprint supports downloading wasm plugins and loading them from your file system.

**Comment by dsherret** [comment]
I just meant that it’s possible to download a `.wasm` file and reference it locally. Like you could download a plugin to the same directory as your dprint config file then specify:

```json
{
  “plugins”: [
    “./some-plugin-file.wasm”
  ]
}
```

Plugins are cached in their compiled form. I forget in what directory on mac (I’m just on my phone at the moment)… I think `$HOME/Library/Caches/dprint`. It can be changed by setting the `DPRINT_CACHE_DIR` environment variable.
