### ISSUE TITLE
the https://plugins.dprint.dev/ website is not accessible 

### ISSUE THREAD

**Issue by hemedani** [dprint/dprint#461]
any version of the wasm plugin is not accessible

**Comment by dsherret** [comment]
What country are you in? Which wasm plugin doesn’t work for you? Could you give an example? Is it the entire site or just wasm plugins?

**Comment by hemedani** [comment]
its entire website is not available
I'm in Iran, but I'm using a VPN from us

**Comment by hemedani** [comment]
it's worked know
thanx

**Comment by dsherret** [comment]
Weird. I didn't do anything 😅

Note that dprint's CLI will respect the `HTTPS_PROXY` environment variable and so maybe if that's set it could cause issues in some cases.

**Comment by dsherret** [comment]
Seems like this is no longer an issue.
