### ISSUE TITLE
Better rust interface for wasm plugins

### ISSUE THREAD

**Issue by malobre** [dprint/dprint#462]
The current `generate_plugin_code` macro is not ideal:
- it leaks linting errors / warnings (`unused_must_use`, `clippy::mut_from_ref`),
- it requires a type named `Configuration` to be in-scope,
- `format_with_host` should return a `Result<Option<String>, _>` where:
  -  `Ok(None)` indicate no changes were made,
  -  `Ok(Some(_))` indicate that the text was correctly formatted,
  - `Err(_)` indicate an error.

`PluginHandler`:
- `get_license_text` could be a `const LICENSE: &'static str = ".."`;
- having to manually resolve config from a `ConfigKeyMap` seems superfluous,
  should be able to use any struct that implements `serde::DeserializeOwned`.

I also have some ideas for `PluginInfo`.

@dsherret I'd like to work on a better macro / interface for rust wasm plugins, are you open to such a PR ?

**Comment by malobre** [comment]
Here's a more concrete proposal:

## Replace `PluginHandler` and `PluginInfo` with new trait `Plugin`

<details>

  ```rust
  pub trait Plugin<H: Host> {
      type Config: Serialize + DeserializeOwned;
      type Error: std::error::Error;
  
      const NAME: &'static str;
      const VERSION: &'static str;
      const LICENSE: &'static str;
      const HELP_URL: &'static str;
      const SCHEMA_URL: &'static str;
      /// The file names this plugin should format.
      const FILE_NAMES: &'static [&'static str];
      /// The file extensions this plugin should format.
      const FILE_EXTENSIONS: &'static [&'static str];
  
      fn format(
          path: PathBuf,
          content: String,
          config: Self::Config,
          host: &H,
      ) -> Result<Option<String>, Self::Error>;
  }
  ```
  ```rust
  #[derive(Debug)]
  pub struct HostError;
  impl std::fmt::Display for HostError { /* --snip-- */ }
  impl std::error::Error for HostError {}
  
  // This would replace `format_with_host`.
  pub trait Host {
      fn format<C: Serialize + DeserializeOwned>(
          path: PathBuf,
          content: String,
          config: C,
      ) -> Result<Option<String>, HostError>;
  }
  ```
</details>

## Rework `generate_plugin_code` macro

- Rename to `wasm_plugin`
- Simplify usage:
  ```rust
  wasm_plugin!(MyPlugin); // Where MyPlugin impl `Plugin`
  ```
- Ensure that the macro does not generate lints errors / warnings.

## Example plugin

<details>

```rust
#[derive(serde::Serialize, serde::Deserialize)]
struct MyPluginConfig;

#[derive(Debug)]
struct MyPluginError;

impl std::fmt::Display for MyPluginError { /* --snip-- */ }
impl std::error::Error for MyPluginError {}

struct MyPlugin;

impl Plugin for MyPlugin {
    type Config = MyPluginConfig;
    type Error = MyPluginError;

    const NAME: &'static str = env!("CARGO_PKG_NAME");
    const VERSION: &'static str = env!("CARGO_PKG_VERSION");
    const LICENSE: &'static str = include_str!("../LICENSE");
    const HELP_URL: &'static str = "https://example.com";
    const SCHEMA_URL: &'static str = "https://example.com";
    const FILE_NAMES: &'static [&'static str] = &[];
    const FILE_EXTENSIONS: &'static [&'static str] = &["ext1", "ext2", "ext3"];

    fn format(
        path: PathBuf,
        content: String,
        config: Self::Config,
        host: &Host,
    ) -> Result<Option<String>, Self::Error> {
        todo!()
    }
}
```
</details>

**Comment by dsherret** [comment]
Yes, some changes here would be great, but not all of them. Let me know if I missed anything:

> it leaks linting errors / warnings (unused_must_use, clippy::mut_from_ref),

Yes, we should fix these issues and a PR fixing them would be great.

> it requires a type named Configuration to be in-scope,

We should fix that to use the fully qualified name.

> format_with_host should return a Result<Option<String>, _> where:

Yes, that change would be good

> get_license_text could be a const LICENSE: &'static str = "..";

I'd rather the strings not be `&'static` in any scenario because there might be scenarios where someone wants to dynamically generate those and cloning the strings should be very cheap. The license text is only requested from plugins when someone does `dprint license` in the CLI. I think the current interface is fine and not worth the effort changing for the most part so I'd like to keep `PluginInfo`

> having to manually resolve config from a ConfigKeyMap seems superfluous, should be able to use any struct that implements serde::DeserializeOwned.

Seems reasonable.

> Rename to wasm_plugin

Yup!

> Simplify usage

Yes, thank you, that would be good!

> `trait Host`

Why would this function be moved to a trait?

> `type Error: std::error::Error;`

Seems reasonable.

**Comment by malobre** [comment]
>> `trait Host`
>
> Why would this function be moved to a trait?

Moving `format_with_host` to `Host::format` would allow future expansion (via `Host`) without changing `Plugin::format` signature.

**Comment by malobre** [comment]
As for all the `&'static str`:
I view all those properties as metadata, like what you would find in a `Cargo.toml` for rust crates. From this POV I believe it makes sense for them to be `&'static str`.

**Comment by dsherret** [comment]
> Moving format_with_host to Host::format would allow future expansion (via Host) without changing Plugin::format signature.

Cool. That would be good!

> I view all those properties as metadata, like what you would find in a Cargo.toml for rust crates. From this POV I believe it makes sense for them to be &'static str.

I don't think it's worth the restriction it brings. Cloning the strings is super cheap in the case of the data on `PluginInfo`.

**Comment by malobre** [comment]
Also since we're sending data through a shared buffer that is heap allocated anyway, it makes sense to return a `String`.
So, let's keep `PluginInfo`:

```rust
pub trait Plugin<H: Host> {
    type Config: Serialize + DeserializeOwned;
    type Error: std::error::Error;

    fn metadata() -> PluginInfo;

    fn format(
        path: PathBuf,
        content: String,
        config: Self::Config,
        host: &H,
    ) -> Result<Option<String>, Self::Error>;
}
```

What do you think ?

**Comment by dsherret** [comment]
@malobre I think we still need the existing `resolve_config` and for `format` to take the resolved config as a reference? It should be possible for plugins to fail config resolution and someone still be able to use them for formatting and to have two distinct steps for this. Also, maybe we can just do `info` instead of `metadata` to keep it consistent with `PluginInfo`? Other than that, looks good!

**Comment by malobre** [comment]
I've been pondering for the past few days and have some thoughts I'd like to share:
- Will messing with the repo I found that not being able to use `cargo fmt` for formatting is a real pain, `dprint fmt` & `cargo fmt` should be configured to output the same code (I mean the code in this repo, not dprint in general).
- Most of the macro complexity comes from plugins having to hold a state, the WASM interface could be changed to something like this (where the state is held by dprint):
    ```rust
    // Interface exposed by dprint.
    extern "C" {
        // arg: UTF-8 string.
        fn metadata_callback(ptr: *const u8, len: usize);
        // arg: UTF-8 string
        fn license_callback(ptr: *const u8, len: usize);
        // arg: UTF-8 string, null ptr if no changes.
        fn format_callback(ptr: *const u8, len: usize);
        // arg: UTF-8 string
        fn error_callback(ptr: *const u8, len: usize);
    
        // Allow plugins to format foreign languages.
        // `path`, `content` & `config` are UTF-8 strings.
        // This will call `host_format_callback` on success.
        fn format(
            path_ptr: *const u8,
            path_len: usize,
            content_ptr: *const u8,
            content_len: usize,
            config_ptr: *const u8,
            config_len: usize
        );
    }
    
    // Interface exposed by a plugin.
    extern "C" {
        // arg: UTF-8 string, null ptr if no changes.
        fn host_format_callback(ptr: *const u8, len: usize);

        // Must call `metadata_callback` with metadata json-serialized as a UTF-8 string.
        fn metadata();
        // Must call `license_callback` with a UTF-8 string.
        fn license();
    
        // Json-deserialize a config from a UTF-8 string.
        // On success returns a ptr to the config.
        // On failure, must call `error_callback` and return a null ptr.
        fn deserialize_config(ptr: *const u8, len: usize) -> *const PluginConfig;

        // Explicitly drop a config.
        fn drop_config(ptr: *const PluginConfig);
    
        // `path` & `content` are UTF-8 strings.
        // On success, must call `format_callback`.
        // On failure, must call `error_callback`.
        fn format(
            path_ptr: *const u8,
            path_len: usize,
            content_ptr: *const u8,
            content_len: usize,
            config_ptr: *const PluginConfig,
        );
    }
    ```
    This would make a plugin macro trivial to implement, mostly making sure pointers are not null and that strings really are UTF-8.

**Comment by dsherret** [comment]
> Will messing with the repo I found that not being able to use cargo fmt for formatting was a real pain, dprint fmt & cargo fmt should be configured to output the same code (I mean the code in this repo, not dprint in general).

Yeah, I can see how that would be annoying. An issue is that I'm using a nightly cargo feature in the dprint.json config, but it seems to not cause any problems to exclude it from the .rustfmt.toml so I added one.

> Most of the macro complexity comes from plugins having to hold a state, the WASM interface could be changed to something like this (where the state is held by dprint):

I'd rather not do any breaking changes to the plugin interface at this point except to support new use cases or if there's a considerable increase in performance shown by a different interface. A new use case in the future might be supporting Wasm threads once it's more stabilized.

On a sidenote, I'm not sure that interface would work for very large files when passing string data back and forth between shared memory. I have a limited understanding of Wasm though.

**Comment by malobre** [comment]
> I'd rather not do any breaking changes to the Wasm interface at this point except to support new use cases or if there's a considerable increase in performance shown by a different interface.

I understand.

> On a sidenote, I'm not sure that interface would work for very large files when passing string data back and forth between shared memory. I have a limited understanding of Wasm though.

Ooh that's why you're chunking your data. That's not necessary, you could just send the original byte array ptr + len to the host and it would work fine (might have to leak it).

**Comment by dsherret** [comment]
> Ooh that's why you're chunking your data. That's not necessary, you could just send the original byte array ptr + len to the host and it would work fine (might have to leak it).

I asked someone about this who knows more about Wasm than me and they said data needed to be transfered across shared memory. I'm also not sure how this would work with JS though it would be interesting to see an example of this working in Rust and in JS if it actually does.

I'm going to close this one in favour of tracking these future improvements in #532. A lot of the stuff mentioned in this issue has been implemented though, so thanks for that! Future improvements to the wasm interface will support cancellation and range formatting.
