### ISSUE TITLE
Error instantiating module

### ISSUE THREAD

**Issue by pnispel** [dprint/dprint#465]
Version: 0.22.0

```
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Error instantiating module: missing requires CPU features: "EnumSet(SSE2 | SSE3 | SSSE3 | SSE41 | SSE42 | POPCNT)"
Had 10 error(s) formatting.
```

**Comment by pnispel** [comment]
{
  "incremental": true,
  "lineWidth": 120,
  "indentWidth": 2,
  "useTabs": false,
  "typescript": {
    "quoteStyle": "preferSingle",
    "semiColons": "asi",
    "trailingCommas": "never"
  },
  "json": {},
  "markdown": {},
  "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json,md}"],
  "excludes": ["**/node_modules", "**/*-lock.json", "**/__generated__/**", "bazel*", "**/.next/**"],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.62.1.wasm",
    "https://plugins.dprint.dev/json-0.14.0.wasm",
    "https://plugins.dprint.dev/markdown-0.12.1.wasm"
  ]
}

**Comment by dsherret** [comment]
@pnispel how did you install dprint and what kind of cpu architecture do you have? (did you happen to install via cargo?)

Also, maybe try doing `dprint clear-cache` and trying again.

Sorry for all the questions. Thanks!

**Comment by pnispel** [comment]
running on an M1 mac. installed through brew and then in our repo we have it installed through npm as well. the npm keeps working pinned at 0.21.2. as a sanity check i downloaded the 0.21.2 binary and tried it in our repo and its fine.

`dprint clear-cache` fixed it regardless. thank you!

**Comment by dsherret** [comment]
@pnispel ok great! Thanks and I opened #466 which should help prevent this in the future.
