### ISSUE TITLE
dprint ignores excludes settings if files are passed directly (lint-staged)

### ISSUE THREAD

**Issue by pnispel** [dprint/dprint#473]
we use dprint with lint staged:

```
//dprint.json
{
  "incremental": true,
  "lineWidth": 120,
  "indentWidth": 2,
  "useTabs": false,
  "typescript": {
    "quoteStyle": "preferSingle",
    "semiColons": "asi",
    "trailingCommas": "never"
  },
  "json": {},
  "markdown": {},
  "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json,md}"],
  "excludes": ["**/node_modules", "**/*-lock.json", "**/__generated__/**", "bazel*", "**/.next/**"],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.62.1.wasm",
    "https://plugins.dprint.dev/json-0.14.0.wasm",
    "https://plugins.dprint.dev/markdown-0.12.1.wasm"
  ]
}
```
```
//package.json
"lint-staged": {
    "**/*.{ts,tsx,js,jsx,cjs,mjs,json,md}": "dprint fmt"
  },
```

lint-staged will call dprint with staged filenames, but the problem is when those filenames are also part of the excluded files

ex:
`dprint fmt ./__generated__/some-generated-file.ts`

will format that file even though it should be excluded. this might be expected behavior, but it'd be nice to have a flag or setting to respect the excludes config even if files are passed by name

**Comment by dsherret** [comment]
Related #258.

Yeah, I think the behaviour here should be changed to exclude these. I opened #474.
