### ISSUE TITLE
Avoid formatting git symlinks on Windows

### ISSUE THREAD

**Issue by davidkna** [dprint/dprint#477]
Version: 0.22.2

Symlinks in git repositories on Windows might not be present as actual file-system symlinks, but as a text files containing the destination path. These files should not be formatted by dprint. For instance, right now dprint may add a trailing newline to these files.

**Comment by dsherret** [comment]
Do you have more information about what "git symlinks" are on Windows? I'm having trouble searching for it. They're different than normal symlinks?

**Comment by davidkna** [comment]
With git symlinks, I just meant files stored in a git repository which git is treating as having a symlink file type.

In the default config, Windows does not allow creating symlinks without admin rights, which is why git on Windows will default to creating these placeholder files containing the target path instead of symlinks. [The GitHub UI](https://github.com/starship/starship/blob/master/docs/guide/README.md) will also show them like this.

**Comment by dsherret** [comment]
> Now in Windows 10 Creators Update, a user (with admin rights) can first enable [Developer Mode](https://msdn.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development), and then any user on the machine can run the mklink command without elevating a command-line console. https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

It looks like people just need to enable developer mode on Windows (though they need admin rights to enable that).

If these are git specific files, then I think just add these files to the excludes list? Are there a lot of them? I don't like dprint having knowledge about other tools... I'm somewhat reluctant to even add support for .gitignore though I'll probably end up doing that (see #378). Maybe this could added when doing that though I'm not sure it's worth it given these files can be ignored in the excludes list.

**Comment by davidkna** [comment]
Ok, that will work for me.
