### ISSUE TITLE
I made something for gitlab ci

### ISSUE THREAD

**Issue by midnightexigent** [dprint/dprint#491]
Hi, this project is awesome ! 

So I went ahead and worked on a little [something](https://gitlab.com/midnightexigent/dprint-ci) to easily use `dprint` from gitlab ci

Feel free to document it/link it in the website.. people might be interested

Also any feedback is appreciated :)

**Comment by dsherret** [comment]
Thanks a lot @midnightexigent! I added this to the website :)

By the way, is this a template people would use? https://gitlab.com/midnightexigent/dprint-ci/-/blob/master/dprint.json It looks really good, but I'm going to do a release this weekend (maybe tonight) that will break all the previous process plugins like dprint-plugin-exec. They'll become much more efficient after this change, but will need to be upgraded to the latest version to work with the CI (too much work to maintain backwards compatibility unfortunately). Also, I'm currently rewriting the prettier plugin. It will be way faster to use that than dprint-plugin-exec in that scenario: https://github.com/dprint/dprint-plugin-prettier/pull/14

**Comment by midnightexigent** [comment]
Hi and thanks for the feedback

> By the way, is this a template people would use? https://gitlab.com/midnightexigent/dprint-ci/-/blob/master/dprint.json 

That's the default if no `dprint.json` or `.dprint.json` are detected

---

> I'm going to do a release this weekend (maybe tonight) that will break all the previous process plugins like dprint-plugin-exec

Do I need to update anything in the default `dprint.json` or just upgrade the `dprint` that used by the CI ?

---

> Also, I'm currently rewriting the prettier plugin. It will be way faster to use that than dprint-plugin-exec in that scenario: https://github.com/dprint/dprint-plugin-prettier/pull/14

Noted, I'll keep an eye out for that and update the default `dprint.json` accordingly when it lands
