### ISSUE TITLE
Add css and vue plugin to website

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#492]
More just a note about in progress plugins to contribute to. Please don't submit a PR for this as I will do it later.

**Comment by some-user123** [comment]
Any update on the status of a vue plugin? Would love to format vue sfc :-)

**Comment by g-plane** [comment]
I've created plugins for formatting CSS and Vue:

- [Malva](https://github.com/g-plane/malva) for CSS/SCSS/Sass/Less
- [markup_fmt](https://github.com/g-plane/markup_fmt) for HTML/Vue/Svelte

**Comment by g-plane** [comment]
@dsherret Hi, can we add those 3rd-party plugins for CSS and HTML/Vue/Svelte to dprint website? Many people are looking for using dprint to format CSS and HTML/Vue/Svelte, but they're hard to find them.

**Comment by dsherret** [comment]
@g-plane I'm very sorry. I get so many notifications that I miss a lot. I am just seeing this now and the plugins seem awesome! Would you be willing to open a pull request to add both malva and markup_fmt to the website?

**Comment by g-plane** [comment]
Should I add a page like this? https://dprint.dev/plugins/json/

**Comment by dsherret** [comment]
Yes, please (ex. `https://dprint.dev/plugins/malva`). Thanks!
