### ISSUE TITLE
got error when use local plugin wasm file

### ISSUE THREAD

**Issue by iulo** [dprint/dprint#499]
Version: 0.24.1

run:
```bash
pnpm dprint fmt --plugins ./typescript-0.66.0.wasm -- ./src/**/*.ts
```

got error:
```
Error resolving plugin **hidden my path**/typescript-0.66.0.wasm: WebAssembly translation error: Error when converting wat: expected at least one module field
     --> <anon>:1:1
      |
    1 | 
      | ^
```

**Comment by iulo** [comment]
I made a stupid mistake, `curl -O` didn't download the full file. After `curl -LO` get the plugin file, everything work fine.Thanks  for your kindness

**Comment by dsherret** [comment]
Ok, great to hear. No problem! Done stuff like that many times myself 😄

I wonder though if the error message could be improved here. I will look into it later.
