### ISSUE TITLE
--stdin make terminal hang

### ISSUE THREAD

**Issue by iulo** [dprint/dprint#500]
Version: 0.23.1   

installed by homebrew

when run `dprint fmt --stdin test.ts` in terminal(like mac item2), nothing output and the terminal hang
![record](https://user-images.githubusercontent.com/6769037/161002881-3189ed74-53a7-4389-9ec3-f9d3a6a7f4e5.gif)

**Comment by iulo** [comment]
I misunderstood the usage. 
`cat test.ts|dprint fmt --stdin test.ts` work

**Comment by zyfyy** [comment]
<img width="807" alt="image" src="https://github.com/dprint/dprint/assets/1721417/406251ba-6847-4379-b076-fda1e591d6ab">
`dprint fmt --stdin` not work the same as `dprint check` or `dprint fmt`

**Comment by dsherret** [comment]
@zyfyy would you be able to open a separate issue with a reproduction that I could easily reproduce (ex. the file text not as a screenshot)? The issue you mentioned doesn't seem related to this issue.
