### ISSUE TITLE
feat: `dprint upgrade` to upgrade to the latest dprint version

### ISSUE THREAD

**Issue by lts20050703** [dprint/dprint#512]
Every time I want to upgrade to the latest version I have to go to https://dprint.dev/install/ then copy paste the install script to PowerShell
The dprint installation process looks similar to deno installation process, so I hope you guys can look at `deno upgrade` code to write your own `dprint upgrade` code!

**Comment by azzamsa** [comment]
Wow! :tada: 

I never know this was a thing. I always use `cargo install-update -a`. Compiling Rust project takes long time for old machine. So `dprint upgrade` was a breeze. I hope other Rust CLI app have the similar feature.
