### ISSUE TITLE
Consider explicitly setting a foreground color when setting background colors in output

### ISSUE THREAD

**Issue by quodlibetor** [dprint/dprint#523]
When I run `dprint check` in my terminal, I get output that is hard to read:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/277161/165206685-0ca7eec4-bd57-4e66-895d-c3d83c84b90d.png">

I don't believe that this green is any of my named colors, so I believe that you're using a 256 or truecolor palette. It would be nice if you could explicitly set the foreground when you set the background.

Thanks for a great tool!

```
$ dprint --version
dprint 0.27.0
```

**Comment by dsherret** [comment]
Thanks for reporting this! I never noticed this because my terminal seemed to be automatically changing the text color from white to black to make it easier to read.

**Comment by quodlibetor** [comment]
Thanks! Yeah some terminals have accessibility things like minimum contrast levels which should prevent issues like this.
