### ISSUE TITLE
Cache path & key

### ISSUE THREAD

**Issue by marksamman** [dprint/dprint#524]
I couldn't find an option to specify the cache path or key.

GitLab CI seems to not support caching folders outside the project directory (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/327, https://stackoverflow.com/questions/53953122/gitlab-ci-cache-no-matching-files). It would be great if it was also possible to specify a custom cache key.

**Comment by lts20050703** [comment]
Probably better to do it as a environment variable instead of cli flag, something like `DPRINT_CACHE_DIR`

**Comment by dsherret** [comment]
This is possible today by setting a `DPRINT_CACHE_DIR` environment variable. I'm guessing you would set it to something like `$HOME/.dprint`.

Sorry, this is in `dprint help`, but I didn't have this on the website in the setup instructions. I've just added it now (should be live in a few minutes https://dprint.dev/setup/). I'll add better CI caching instructions in the future.

**Comment by marksamman** [comment]
Nice! `DPRINT_CACHE_DIR` solves my problem without workarounds :)
