### ISSUE TITLE
dprint requires unzip to be installed for npm install

### ISSUE THREAD

**Issue by vedantroy** [dprint/dprint#526]
Because dprint requires unzip in order to be installed, this prevents projects using it from deploying on fly.io, even if dprint is just a developer dependency.

This is not a big deal, but figured I'd let you know.

https://community.fly.io/t/modify-config-for-remix-app/4938

**Comment by vedantroy** [comment]
Closed because I just realized fly.io gives a Dockerfile

**Comment by dsherret** [comment]
I’m going to reopen because I’d like to fix this for the npm package. I feel like it should use an npm dependency to unzip instead of relying on unzip.

**Comment by vedantroy** [comment]
Got it. If that's the case, then dprint also requires having curl installed.

**Comment by dsherret** [comment]
@vedantroy this is implemented now. Let me know if you run into any issues.
