### ISSUE TITLE
Future improvements to plugin and editor interfaces

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#532]
This is a tracking issue for possible improvements to the editor and plugin interfaces.

**All**

- maybe - the plugin should specify if it can handle range formatting in the "can format" message (ex. 0 = no, 1 = yes, 2 = yes & can range format)
- maybe - should support formatting multiple ranges

**Wasm Plugins**

- must - range formatting similar to process plugins
- must - cancellation token similar to process plugins
- must - multiple configs loaded per plugin similar to process plugins
- maybe - async host formatting and therefore async formatting (doesn't seem necessary?)
- must - updates from https://github.com/dprint/dprint/issues/716
- must - updates from https://github.com/dprint/dprint/issues/714
- must - Get entire format result out of memory at once.

Additional:

- Send log level on initialize so plugins can output with verbose logging.
- Send past version with upgrade message (if not already done)
- Logging with log level in wasm plugins
- Ability for plugins to tell if no_color and if a tty. Probably send on init
- Maybe ability for Wasm plugin to import another wasm plugin via Wasm imports?
- Wasm schema should not require instantiating a wasm module (it should be figured out by just analyzing the import names)
- Ability for plugins to do comparisons with language aware algorithms (ex. for sorting imports).

**Comment by g-plane** [comment]
I wish one plugin can know the information of existence of another plugins. This feature is mainly helpful when using `format_with_host` with setting additional config: we can specify different additional config by detecting what other plugins are used in someone's config.

**Comment by dsherret** [comment]
@g-plane I added that point to https://github.com/dprint/dprint/pull/858

**Comment by dsherret** [comment]
@g-plane actually, would you be able to open an issue for this with a real example? I kind of think a “push”/“broadcast” kind of model is better and less complicated. The plugin receiving the information would just need to know how to interpret it.

**Comment by g-plane** [comment]
What information or example should I provide?

**Comment by dsherret** [comment]
Just a real world scenario where that would be useful. I don’t fully understand the use case.

**Comment by g-plane** [comment]
See #866 .
