### ISSUE TITLE
dprint vscode extension does not work on .js files at root even though it should

### ISSUE THREAD

**Issue by nikitavoloboev** [dprint/dprint#535]
I have this config:

```
{
  "typescript": {
    "semiColons": "asi"
  },
  "json": {
  },
  "markdown": {
  },
  "toml": {
  },
  "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json,md,toml}"],
  "excludes": [
    "**/node_modules",
    "**/*-lock.json"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.68.3.wasm",
    "https://plugins.dprint.dev/json-0.15.2.wasm",
    "https://plugins.dprint.dev/markdown-0.13.2.wasm",
    "https://plugins.dprint.dev/toml-0.5.4.wasm"
  ]
}
```

I then have project open with file `vite.config.js`. I assume if I press save on it, dprint will format it but it doesn't. Or at least it doesn't respect the `"semiColons": "asi"` setting.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/6391776/169669161-7cd705bd-4f97-41bf-bb09-e9b1a080af8a.png">

However in `root.jsx` in same project dprint works and strips the `;` so dprint works.

<img width="564" alt="image" src="https://user-images.githubusercontent.com/6391776/169669169-460cdc4f-a47c-4bb5-a6d1-3aa7538ac581.png">

**Comment by dsherret** [comment]
Did you follow the setup instructions? https://marketplace.visualstudio.com/items?itemName=dprint.dprint

**Comment by nikitavoloboev** [comment]
Oh yes I had this:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/6391776/169669310-889c8cfe-d6c3-4ab7-b01e-24aa5e5cd123.png">

I assumed it would read the dprint config that did have `js` included for me.

If I do this:

```
{
  "editor.defaultFormatter": "dprint.dprint",
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.defaultFormatter": "dprint.dprint",
    "editor.formatOnSave": true
  }
}
```

It does start formatting JS files. I thought:

` "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json,md,toml}"],`

Should be enough?

**Comment by dsherret** [comment]
Do you  have another formatter configured in your vscode user settings for JavaScript?

**Comment by nikitavoloboev** [comment]
Oh yes I did have a line there that used prettier. My bad, thank you for the help ♥️

**Comment by dsherret** [comment]
That's no problem! Hopefully this information will help someone else in the future.
