### ISSUE TITLE
Support CSS formatting without prettier plugin

### ISSUE THREAD

**Issue by nikitavoloboev** [dprint/dprint#536]
Currently the only way to format CSS if you go all in with using dprint for all formatting is via prettier plugin. Would be lovely for dprint to support CSS formatting natively.

**Comment by g-plane** [comment]
I've created a parser that can parse CSS/SCSS/Sass/Less: https://github.com/g-plane/raffia, so I think it's possible to achieve that.

**Comment by saona-raimundo** [comment]
I think, I have not tried it, that the CSS plugin is ready(?) 

There is a [`dprint_plugin_css`](https://crates.io/crates/dprint_plugin_css) crate in crates.io, and the issue #492.
`dprint_plugin_css` code forwards formatting to the [lightningcss](https://github.com/parcel-bundler/lightningcss) crate.

**Comment by g-plane** [comment]
Technically, lightningcss doesn't store too much source code information because it produces a special structure which is not AST, but similar to IR, which means, it will change the code you written in an unexpected way.

**Comment by saona-raimundo** [comment]
I looked for examples of weird behaviours. This is what I found.
- Reordering of rules and sorting properties can not be turned off. 
  - lightingcss [issue 276](https://github.com/parcel-bundler/lightningcss/issues/276) and [issue 231](https://github.com/parcel-bundler/lightningcss/issues/231)
- Rounding of numbers (only keeping 6 digits)
  - cssparser [issue 173](https://github.com/servo/rust-cssparser/pull/173)
  - caused problems in [z-index usage](https://github.com/parcel-bundler/lightningcss/issues/170)

This is a small [lightingcss playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A3276800%2C%22firefox%22%3A3276800%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%5Cn%20%20transition%3A%20background%20200ms%3B%5Cn%5Cn%20%20margin-left%3A%20100em%3B%5Cn%20%20margin-right%3A%20100.0004em%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.13.1%22%7D) showing the behaviour.

**Comment by devongovett** [comment]
hi, I am the author of lightningcss. You are correct that it is not really designed for formatting use cases. During parsing, a lot of values are normalized such that their original authored format is no longer available. For example, colors may be converted from `rgb()` to hex, defaults removed from shorthands, etc. Unless you want the output of the formatter to also normalize the CSS, I'd recommend using something much simpler for this.

**Comment by matthew-dean** [comment]
@devongovett 

> During parsing, a lot of values are normalized

Just curious, what was the reason for this approach vs. a normalization / node visitor phase after capturing a CST? You could still do normalization in creating an AST, but then it would be pluggable for formatting scenarios.

**Comment by devongovett** [comment]
Mainly performance, but it also guarantees that any value that is parsed is always fully normalized which makes building transforms easier. This is exactly how browsers parse CSS.

**Comment by g-plane** [comment]
@matthew-dean Though LightningCSS AST isn't suitable for formatting, it's good at making optimizing CSS much easier. I think it's OK for its design goal.

**Comment by disrupted** [comment]
Hi, I have created a standalone plugin: [dprint-plugin-css](https://github.com/disrupted/dprint-plugin-css). It uses https://github.com/g-plane/raffia and is therefore completely independent from Prettier. I think it would be nice to migrate some of Prettier's formatting rules over time. Contributions welcome :)

**Comment by g-plane** [comment]
@disrupted Wow, great thanks! That's what I really want to do, but I don't understand how to create a dprint plugin and have enough time. [A paper](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf) which Prettier referred may help you.

**Comment by g-plane** [comment]
I've created a plugin as well: [malva](https://github.com/g-plane/malva). It supports CSS/SCSS/Sass/Less.

Usage:

- Run `dprint config add g-plane/malva`
- Try it on [playground](https://malva-play.vercel.app/)
