### ISSUE TITLE
StripPathPrefix error being thrown from glob matchers.

### ISSUE THREAD

**Issue by ryan-rushton** [dprint/dprint#540]
We are seeing the following error being thrown occasionally in the IntelliJ plugin. 

```
INFO - .dprint.services.DprintService - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', crates/dprint/src/utils/glob/glob_matcher.rs:81:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Unfortunately I don't know how to reproduce this reliably at the moment but maybe its something trivial we can guard against [here](https://github.com/Canva/dprint/blame/main/crates/dprint/src/utils/glob/glob_matcher.rs#L80).

**Comment by dsherret** [comment]
Very strange. I added some extra logging for this in #541 and that will be in 0.30 (doing a release now).

**Comment by dsherret** [comment]
#541 will provide more logging about this in the future so if it happens let's reopeng if it happens again with that (also, seems like this might be a bug in a fork of dprint).

**Comment by ryan-rushton** [comment]
Thanks @dsherret!
