### ISSUE TITLE
Building docker image with aarch64 build fails due to mismatching checksum

### ISSUE THREAD

**Issue by nikolai-tise** [dprint/dprint#548]
After upgrading to version `0.30.1` building docker image with arm architecture causes the build to fail with 

`npm ERR! Downloaded dprint zip checksum did not match the expected checksum (Actual: 69875e044b831ba34df72fbc9009f269909cf72d18485d876690ee9f51a5dfd5, Expected: c8b45ca831b742c3555060e4895e4adcd03894a2ad017f0fb9919adb99060197)` 

Seems like its expecting the `x86_64` checksum even when using `aarch64`

**Comment by dsherret** [comment]
Thanks for reporting this @nikolai-tise! I just added linux arm64 builds this weekend. Could you try it out in 0.30.3 (just published)?

**Comment by nikolai-tise** [comment]
`0.30.3` is working just fine on linux arm64. Thanks for fixing this so quickly @dsherret!
