### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by stephenh** [dprint/dprint#559]
I've been replacing prettier with dprint in our ~large-ish code generation pipeline, and really enjoying seeing ~70-80% of the flamegraph go away. :-) Thank you!

The last file format I still need to go through prettier for is GraphQL, so it'd be great to see a `@dprint/graphql`.

**Comment by dsherret** [comment]
That would be nice and probably not too bad to do. Would just have to find the time.

Also, thanks for sponsoring, @stephenh!

**Comment by g-plane** [comment]
I've made a GraphQL plugin: https://github.com/g-plane/pretty_graphql

Run

```bash
dprint config add g-plane/pretty_graphql
```

to install.

**Comment by stephenh** [comment]
Awesome @g-plane , thank you! Fwiw if it could eventually be bundled as part of `dprint-node` (to avoid the wasm plugin load step), that would be even more amazing/out-of-the-box (just given how common GraphQL is).

**Comment by predaytor** [comment]
@g-plane perfect! but can we support typescript files here by calling `graphql(``)` function?
```ts
import { graphql } from 'gql.tada';

export const ProjectsQuery = graphql(`
	query Projects {
		projects {
			nodes {
				id
			}
		}
	}
`);
```

**Comment by dsherret** [comment]
@predaytor it's something that could be added to dprint-plugin-typescript: https://github.com/dprint/dprint-plugin-typescript/issues/658
