### ISSUE TITLE
are plugins invoked on-demand?

### ISSUE THREAD

**Issue by tomdavidson** [dprint/dprint#578]
Hello, looking at escaping prettier's performance - most of the time.

If I use prettier plugin to format file types that dprint does not do, will I still be running prettier every time or only on demand when that file extension is passed to dprint?

**Comment by dsherret** [comment]
I believe it will only launch prettier in the following cases:

1. It's never cached the plugin.
2. A file that matches for prettier has changed.
3. Any plugin config has changed (which will bust the cache I think).

You can run with `dprint fmt --verbose` to see what it's doing.
