### ISSUE TITLE
clarify plugin precedence 

### ISSUE THREAD

**Issue by tomdavidson** [dprint/dprint#579]
> The order of the plugins in this array defines the precedence. If two plugins support the same file extension then define the one you want to format that extension with first.

A file will only be processed by one plug-in?
And its the first matching glob in the plug-in list?

This means we do not have to attempt set theory in matching and negating globs for each plugin? Such that typescript files would not make it to the prettier plugin if the plugins are ordered like this:

```json
[
        "https://plugins.dprint.dev/exec-0.3.1",
        "https://plugins.dprint.dev/typescript-0.78.0.wasm",
        "https://plugins.dprint.dev/json-0.16.0.wasm",
        "https://plugins.dprint.dev/markdown-0.14.1.wasm",
        "https://plugins.dprint.dev/toml-0.5.4.wasm",
        "https://plugins.dprint.dev/dockerfile-0.3.0.wasm",
        "https://plugins.dprint.dev/prettier-0.13.0"
]
 ```

**Comment by dsherret** [comment]
> This means we do not have to attempt set theory in matching and negating globs for each plugin?

Yes, the order of the plugins array will dictate which plugin a file gets formatted with.

>  Such that typescript files would not make it to the prettier plugin if the plugins are ordered like this

Yes, the typescript files would not be formatted with prettier in that case if ordered like that.

> A file will only be processed by one plug-in?

Not necessarily. If you set an "associations" for multiple plugins and a file matches for multiple plugins, then it will format the file in series using all the plugins it matches against. See https://dprint.dev/config/ and search for "associations"

Also, I'm working on #580 right now which slightly changes the behaviour of associations.

**Comment by tomdavidson** [comment]
> Not necessarily. If you set an "associations" for multiple plugins and a file matches for multiple plugins, then it will format the file in series using all the plugins it matches against.

This is exactly what I was after and I now see I missed an important part of the docs "...by associating a certain file pattern to one or multiple plugins."

Thanks for the heads up on #580 too.
