### ISSUE TITLE
Using system certificates for HTTPS connections

### ISSUE THREAD

**Issue by Pgolik** [dprint/dprint#591]
Hello,
First of all, I am using this plugin, and really love simplicity and extensibility of it. Greate job!

ERROR:
While using dprint I have encountered an issue with certificates: 
`tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`.

FEATURE:
I would appreciate, if there would be a possibility to use system certs while downloading plugins.

ROOT CAUSE:
I am working in a project which is enclosed, and uses artifactory to store all required dependencies which currently in use. Artifactory got a set of certificates, which are added to system certs. Due to fact that those certificates are not in `webpki_roots::TLS_SERVER_ROOTS` provided by Mozilla, showed error is popping up. 

Thanks in advance 😄

**Comment by tlewowski** [comment]
@dsherret would you be willing to accept a pull request for this? 

It seems like a simple change (adding `native-certs` feature to `ureq` features (`crates/dprint/Cargo.toml`), but if current behavior (fixed list of known certificates) is intended, it'd break.

**Comment by dsherret** [comment]
I don't know enough about certificates to know what the proper behaviour should be here. Do most people use the system certs or mozilla ones? I feel like using system seems better. Maybe let's just do what you suggested and if it breaks anyone then we can make this configurable.

So yeah, a PR would be great. Thanks!

**Comment by tlewowski** [comment]
most mature tools on Linux (git, curl etc.) either use system certs or have their own certificate configuration - so there is at least a possibility of running on a non-public setup (probably corporate networks are the most common case).
I'll issue a PR later today, thanks for the fast response!

**Comment by dsherret** [comment]
Should be fixed in #599. Thanks @tlewowski! I'll do a release hopefully later today.

**Comment by tlewowski** [comment]
@dsherret thank you! This will be useful for teams that are able to use one of the provided OS installers or `cargo`. For teams that use `npm`, we found one more problem with installation behind http proxy: https://github.com/dprint/dprint/issues/603

**Comment by dsherret** [comment]
This is now configurable via the `DPRINT_CERT` and `DPRINT_TLS_CA_STORE` env vars: https://dprint.dev/setup/#tls-certificates
