### ISSUE TITLE
[windows] Command failed with exit code 3221225781 / VCRUNTIME140.dll was not found

### ISSUE THREAD

**Issue by drunkwinter** [dprint/dprint#593]
Version: 0.33.0

I recently reinstalled Windows. And when I tried running dprint via NPM nothing would happen. Tried the same thing with PNPM and it gave me this error `Command failed with exit code 3221225781`. Lastly I tried running the `.exe` and I got the `VCRUNTIME140.dll was not found` popup.

![image](https://user-images.githubusercontent.com/38593134/204662276-b9ae134d-5cc9-4fb2-a4d5-87116684c89c.png)

Shouldn't all the dependencies be installed automatically when installing dprint?

**Comment by dsherret** [comment]
I didn't realize that. For now, please install the latest c++ runtime: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

You didn't get any error messages with npm? That's strange. I'll look into that too.

**Comment by drunkwinter** [comment]
Yeah I already did. Weird enough NPM gave me nothing, which really confused me.

**Comment by drunkwinter** [comment]
Also Windows seems to behave really weird in this situation. When you uninstall the C++ runtime, it still works and the `VCRUNTIME140.dll` is still located in `System32` 😒
