### ISSUE TITLE
Cannot install dprint via npm behind http proxy

### ISSUE THREAD

**Issue by tlewowski** [dprint/dprint#603]
*Action*: running `npm install dprint` in an environment behind a http proxt

*Expected result*: there is a possibility to configure the machine, npm etc. to successfully install dprint

*Actual result*: there are no options that I'm aware of that user can set that would make `dprint` installer respect the proxy setup

*Detailed description:*

From what I understand, when the user runs `npm install dprint`, the downloaded package is really just a stub that is able to then download the actual installer - https://github.com/dprint/dprint/blob/main/deployment/npm/install_api.js triggered by a postinstall step.

However, `install_api.js` directly uses `https.get()` from core Node.js modules - https://nodejs.org/api/https.html#httpsgetoptions-callback

The problem with this approach is that one of the design choices of `https.get()` is to require the developer to explicitly set all the options and properties that will be used by the client, and does not allow for altering behavior via environment variables (or any other global mechanism really). This is a deliberate design choice, and there are a bunch of issues on GH requesting for this feature, but they are all rejected: https://github.com/nodejs/node/issues/1490 https://github.com/nodejs/node/issues/8381

Now, I'm not discussing the choice - Node team decided to do so, so we'll just have to adapt. However, this choice also means that without adding some properties to `options` object (and obfuscating it a little in result - https://stackoverflow.com/a/5810547/2671214 ), or using an external library like https://github.com/gajus/global-agent , all http requests will ignore any proxy configuration that the machine may have. 

This _probably_ can be addressed on the machine level by some smart iptables configuration or monkey-patching dynamic libraries, but these are pretty brutal mechanisms to use a proxy - the usual mechanism (at least in Linux environments) is what dprint binary uses at runtime - HTTP_PROXY and HTTPS_PROXY.

**Comment by dsherret** [comment]
@tlewowski I believe this should be fixed now in 0.34.0 and respect the HTTPS_PROXY and HTTP_PROXY env vars. Let me know if not.
