### ISSUE TITLE
`dprint -V` successful command emit 1 as exit code

### ISSUE THREAD

**Issue by azzamsa** [dprint/dprint#608]
Hi,

`dprint` successful command should emit `0` as the exit code.
For comparison:

```shell
~
❯ just -V
just 1.9.0

~
❯ echo $?
0

~
❯ zoxide -V
zoxide v0.8.3

~
❯ echo $?
0

~
❯ bat -V
bat 0.22.1 (e5d9579)

~
❯ echo $?
0

~
❯ dprint -V
dprint 0.34.0


~
❯ echo $?
1
```

I think it's also the reason my latest CI build that depends on `dprint` fails:
-  https://github.com/azzamsa/islam/actions/runs/3730199419/jobs/6326968407#step:7:12
- https://github.com/azzamsa/zman/actions/runs/3730166776/jobs/6326899242#step:7:12

```
OS: Fedora release 37 (Thirty Seven) x86_64
Kernel: 6.0.12-300.fc37.x86_64
Shell: zsh 5.9
Dprint Version: 0.34.0
```

**Comment by dsherret** [comment]
It seems related just to `-V`. If you use `-v` it's fine.

**Comment by azzamsa** [comment]
Oh, I see thanks!

Thank you for dprint!

**Comment by dsherret** [comment]
I think it is a bug since other tools don't do this. I'll fix it soon.
