### ISSUE TITLE
Install fails on aarch64 due to missing checksum

### ISSUE THREAD

**Issue by alexanderweiss** [dprint/dprint#619]
Version: 0.34.1

In version 0.34, the checksum lookup for linux was updated to always include the linux family, but the checksum in `info.json` doesn't include the family for `aarch64`. It's looking for the key `linux-aarch64-gnu`, but the actual key is `linux-aarch64`. This causes installation to fail.

See https://github.com/dprint/dprint/commit/5a191b8ca1a2c1afc1f82914907a0ed188e1664f#diff-825a2a8dbcab67a42fe0f8bcd69f3b4bc199585cba51c745e16362f4e309191fL200-R146

**Comment by dsherret** [comment]
Thanks for reporting this! Should be fixed in 0.34.4 and I modified the code to mitigate this in the future.

Also, sorry. I don't have a linux aarch64 machine and there are no github action runners for that yet in order to test the release

**Comment by alexanderweiss** [comment]
Thanks for the quick fix! We have in the past used Docker with qemu to build ARM images on Github actions. That should work if you'd really like to have tests for it.
