### ISSUE TITLE
`dprint` as a library ?

### ISSUE THREAD

**Issue by nurmohammed840** [dprint/dprint#631]
I would like to use `dprint` as a crate in my rust project.

My use case is that, My library generate js/ts glue code. And I would like generate formatter string (code).

Sure, I can format code using `dprint` binary, But It has some drawback...

**Comment by dsherret** [comment]
Yes, the plugins are on crates.io. Deno uses it as a rust crate. https://crates.io/crates/dprint-plugin-typescript

Example usage:

https://github.com/denoland/deno/blob/main/cli/tools/fmt.rs
