### ISSUE TITLE
Update ureq from version 2.5.0 to latest (2.6.2)

### ISSUE THREAD

**Issue by reupen** [dprint/dprint#633]
Version: 0.34.4

Hi,

I'm receiving an error from ureq when running dprint on Windows:

```
thread 'main' panicked at 'Failed to add native certificate too root store: UnsupportedCriticalExtension', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ureq-2.5.0\src\rtls.rs:74:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

[This appears to have been fixed in ureq 2.6.0](https://github.com/algesten/ureq/blob/main/CHANGELOG.md) ([pull request](https://github.com/algesten/ureq/pull/564)), therefore it would be good to update ureq to the latest version.

Thanks

**Comment by dsherret** [comment]
Released in 0.34.5
