### ISSUE TITLE
release 0.34.5 did not get completed

### ISSUE THREAD

**Issue by chenrui333** [dprint/dprint#635]
👋 somehow the 0.34.5 release did not get completed (i.e. the tag did not get promoted to be `latest` release), kind of blocks [the homebrew release](https://github.com/Homebrew/homebrew-core/pull/123068) in a semantic way. Thanks!!

**Comment by dsherret** [comment]
Done. I kicked it off, but then forgot to hit publish on the release.

**Comment by chenrui333** [comment]
Thanks @dsherret!
