### ISSUE TITLE
Segfault on macOS, version 0.34.5

### ISSUE THREAD

**Issue by francisbonneau** [dprint/dprint#636]
Version: dprint 0.34.5

Hello, first off thanks for dprint! It's great software.

It was working well for me until recently, but now it seems that after updating to the latest version, now running `dprint fmt` or  `dprint check` will result in a crash...

```
$ dprint fmt "**/*.{ts,tsx,js,jsx,json}"
zsh: segmentation fault  dprint fmt "**/*.{ts,tsx,js,jsx,json}"
```
```
$ dprint check
zsh: segmentation fault  dprint check
```

The behaviour is the same when using it directly in the CLI or with the CLion plugin. I'm on a Macbook pro with a M1 chip.

This is my project `dprint.json config` file:

```
{
    "lineWidth": 120,
    "indentWidth": 4,
    "typescript": {
        "semiColons": "asi"
    },
    "json": {
    },
    "markdown": {
    },
    "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json,md}"],
    "excludes": [
        "**/node_modules",
        "**/*-lock.json",
        "dist"
    ],
    "plugins": [
        "https://plugins.dprint.dev/typescript-0.83.0.wasm",
        "https://plugins.dprint.dev/json-0.17.0.wasm",
        "https://plugins.dprint.dev/markdown-0.15.2.wasm"
    ]
}

```
This is the macOS crash report, that I found in `~/Library/Logs/DiagnosticReports/`

[dprint-crash-report.json.zip](https://github.com/dprint/dprint/files/10757518/dprint-crash-report.json.zip)

**Comment by dsherret** [comment]
How did you install it? Thanks a lot for the crash dump. Looks like it's occuring when deserializing the Wasm (I think). Does it occur after the following is run?

```
dprint clear-cache
```

I need better caching in dprint. The cache system was created very early and I haven't updated it.

**Comment by francisbonneau** [comment]
I installed it using brew. Just tried the clear-cache command and it fixed my issue, dprint fmt now works as expected.

Thank you!

**Comment by dsherret** [comment]
Sorry about that issue. I'm not sure exactly what caused it, but I opened #637 to help minimize it in the future. I'll do a new patch that busts the cache tonight then close this issue.
