### ISSUE TITLE
Make `newLineKind` a global config

### ISSUE THREAD

**Issue by Avasam** [dprint/dprint#658]
"Global Configuration" in https://dprint.dev/config/ does not list `newLineKind`. Given it's present in basically all other configurations, it seems reasonable to me to have it as a global config. With it I could remove my json, markdown, dockerfile and toml sections as that's the only property I have that doesn't match default.

**Comment by dsherret** [comment]
Sorry, it exists. I just didn't have it documented.

**Comment by Avasam** [comment]
Oh neat, alright then.
