### ISSUE TITLE
Support for prebuilt linux aarch64 musl

### ISSUE THREAD

**Issue by ksmithut** [dprint/dprint#659]
I'm attempting to install this this as an `npm` dependency on a node:alpine Docker image, but I get an error:

```
Error downloading dprint zip file. Error: Unknown status code 404 : Not Found
     at ClientRequest.<anonymous> (/app/node_modules/dprint/install_api.js:102:18)
```

I've given that stack trace, it looks like the url it's looking to download the dprint zip file looks something like this:

```
https://github.com/dprint/dprint/releases/download/dprint-aarch64-unknown-linux-musl.zip
```

To reproduce, you can build a docker image with this Dockerfile:

```Dockerfile
FROM node:18-alpine
RUN mkdir -p /app
WORKDIR /app
RUN echo '{"devDependencies":{"dprint":"*"}}' > package.json
RUN yarn install
```

Then run:

```sh
docker build --platform linux/arm64 .
```

I'm running this on an M1 mac, so I'm unsure if running this will work on non-arm devices.

I'm also unsure if this is as easy as just adding it to the list of platforms here https://github.com/dprint/dprint/blob/main/.github/workflows/ci.generate.ts and regenerating that that ci.yaml workflow.

**Comment by dsherret** [comment]
I tried cross compiling it, but haven't been able to get it to work yet in https://github.com/dprint/dprint/pull/665

**Comment by dsherret** [comment]
Failed building in release. Cross compiling on x64 gnu to aarch64 musl seems like a lost cause.

**Comment by dsherret** [comment]
Could someone do me a favour and let me know if the following works? I don't have a machine to test.

* Install script: https://dprint.dev/install/
* Running `dprint -v` after installing
* Does https://github.com/dprint/dprint-plugin-exec work? I know dprint-plugin-prettier won't atm.
* Bonus: does opening an npm project and doing `npm install dprint` work? Does `npx dprint -v` work after doing that?

Thanks!

**Comment by vandamm** [comment]
@dsherret this works for my use case. 
* Installing dprint via npm inside of a Docker on Apple Silicon finished successfully. 
* Running `npx dprint config add exec` and then using exec plugin also worked.
* Prettier plugin errored with `Error resolving plugin https://plugins.dprint.dev/prettier-0.27.0.json: Unsupported CPU architecture: aarch64 (linux-musl)`

**Comment by dsherret** [comment]
Great. Glad to hear it works!

For anyone interested in dprint-plugin-prettier support, please follow https://github.com/dprint/dprint-plugin-prettier/issues/66
