### ISSUE TITLE
`fmt --stdin` not using specified plugin from configuration file when specifying extension with leading period

### ISSUE THREAD

**Issue by leonasdev** [dprint/dprint#667]
Version: 0.35.4

I'm having trouble using `fmt --stdin` with a specified plugin from my configuration file. Despite specifying the plugin in my configuration, it doesn't appear to be used when I run the command.

  I have a configuration file (`dprint.json`) with the following content:
```json
{
  "typescript": {
  },
  "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs}"],
  "excludes": [
    "**/node_modules"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.84.1.wasm"
  ]
}
```

The configuration specifies that the `typescript` plugin should be used to format TypeScript files.

When I run the command:
```bash
echo "function    test()   {} " | dprint fmt --stdin .ts --config ./dprint.json --verbose
```
, I get the following output:

```
[VERBOSE] Reading file: /root/.cache/dprint/cache/plugin-cache-manifest.json
[VERBOSE] Reading file: /root/dprint-test/dprint.json
[VERBOSE] Reading file: /root/.cache/dprint/cache/plugins/dprint-plugin-typescript/0.84.1-2.3.0-x86_64
[VERBOSE] Host formatting .ts - File length: 27 - Plugins: [] - Range: None
function    test()   {}
```

The output indicates that the plugin is not being used. The verbose output shows that no plugin is being loaded or used to format the input.

I'm not sure why the plugin is not being used. Is there something else I need to do to enable the plugin for `fmt --stdin`? Any help or guidance would be greatly appreciated.

Thanks!

**Comment by dsherret** [comment]
Try just doing `dprint fmt --stdin ts`. Does that work? I think the code is broken when specifying an extension with a period.

**Comment by dsherret** [comment]
In that case, there is no matching plugin for json files. You probably need to add the json plugin:

```json
{
  "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json}"],
  "excludes": [
    "**/node_modules"
  ],
  "plugins": [
    "https://plugins.dprint.dev/json-0.17.1.wasm",
    "https://plugins.dprint.dev/typescript-0.84.1.wasm"
  ]
```

**Comment by leonasdev** [comment]
> In that case, there is no matching plugin for json files. You probably need to add the json plugin:
> 
> ```json
> {
>   "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json}"],
>   "excludes": [
>     "**/node_modules"
>   ],
>   "plugins": [
>     "https://plugins.dprint.dev/json-0.17.1.wasm",
>     "https://plugins.dprint.dev/typescript-0.84.1.wasm"
>   ]
> ```

But the file I want to format is a TypeScript file, isn't it? Why would I need a JSON plugin?

**Comment by dsherret** [comment]
@leonasdev sorry, I misread the left side. The issue is that it is specifying `dprint.json` as the filename of the file being piped in. You need to specify that it's a typescript file. For example:

```
cat test.ts | dprint fmt --stdin ts --verbose
# or 
cat test.ts | dprint fmt --stdin test.ts --verbose
```

**Comment by leonasdev** [comment]
> @leonasdev sorry, I misread the left side. The issue is that it is specifying `dprint.json` as the filename of the file being piped in. You need to specify that it's a typescript file. For example:
> 
> ```
> cat test.ts | dprint fmt --stdin ts --verbose
> # or 
> cat test.ts | dprint fmt --stdin test.ts --verbose
> ```

I'd like to confirm if I understood the following section correctly in the docs:
> Formatting Standard Input
> 
> Use dprint fmt --stdin <file-path/file-name/extension> and provide the input file text to stdin. The output will be directed by the CLI to stdout.
> 
> Provide a full file path to format with inclusion/exclusion rules of your dprint configuration file or provide only a file name or extension to always format the file.

Does it mean that I can specify a configuration file to format the contents of stdin, is that correct?

**Comment by dsherret** [comment]
A configuration file may contain multiple plugins. The file path/name/extension provided to the `--stdin` flag describes what kind of file will be provided over stdin so that dprint can select the correct plugin to use based on the rules in the dprint configuration file.

The config file will be auto-discovered or you can specify one via the `--config` flag.

**Comment by leonasdev** [comment]
> A configuration file may contain multiple plugins. The file path/name/extension provided to the `--stdin` flag describes what kind of file will be provided over stdin so that dprint can select the correct plugin to use based on the rules in the dprint configuration file.
> 
> The config file will be auto-discovered or you can specify one via the `--config` flag.

I understand now, thank you for clarifying it for me.
