### ISSUE TITLE
dprint 0.38.0 doesn't work with Yarn Berry (PnP) unless unplugged

### ISSUE THREAD

**Issue by tirr-c** [dprint/dprint#686]
Version: 0.38.0

dprint 0.38.0 tries to copy a binary from platform-specific package into its package directory, which doesn't work with Yarn PnP. 
```console
$ yarn dprint check
EROFS: read-only filesystem, open '/node_modules/dprint/dprint'
```

---

Workaround: you can unplug the package manually. This extracts the zip archive of the package and makes it writable.
```
yarn unplug dprint
```

dprint 0.37.1 had a postinstall script, which forces unplugging of the package.

**Comment by dsherret** [comment]
Sorry about that! Should work in 0.38.1. Let me know if not.
