### ISSUE TITLE
consider de-duplication of effort \ collaboration with https://github.com/numtide/treefmt

### ISSUE THREAD

**Issue by adrian-gierakowski** [dprint/dprint#713]
There seem to be quite a bit of overlay between the 2 projects. 

Treefmt is more limited in scope, but it supports more languages since it simply delegates formatting to 3rd party executables, so adding new formatters seems to be easier than adding new plugins for dprint.

It actually [supports dprint](https://github.com/search?q=repo%3Anumtide%2Ftreefmt-nix+dprint&type=code) already.

**Comment by dsherret** [comment]
> Treefmt is more limited in scope, but it supports more languages since it simply delegates formatting to 3rd party executables, so adding new formatters seems to be easier than adding new plugins for dprint.

dprint supports this scenario through the exec plugin: https://github.com/dprint/dprint-plugin-exec -- I need to update the website to highlight how dprint can be used as a unified formatter more.

Looking briefly at the code for treefmt, there is a lot more going on in dprint to make things fast and work well in an editor.

**Comment by adrian-gierakowski** [comment]
> > Treefmt is more limited in scope, but it supports more languages since it simply delegates formatting to 3rd party executables, so adding new formatters seems to be easier than adding new plugins for dprint.
> 
> dprint supports this scenario through the exec plugin: https://github.com/dprint/dprint-plugin-exec -- I need to update the website to highlight how dprint can be used as a unified formatter more.
> 
> Looking briefly at the code for treefmt, there is a lot more going on in dprint to make things fast and work well in an editor.

Cool, thanks for the quick answer. I wonder if if treefmt devs could learn something from your approach then. Would you be able to briefly summarise the optimisations you've employed? Thanks!

**Comment by dsherret** [comment]
Essentially, dprint is not just shelling out formatting commands to run. It creates pools of plugin instances and then sends the pools files to format.
