### ISSUE TITLE
`dprint` fails due to `dprint-plugin-exec` error: `failed to fill whole buffer`

### ISSUE THREAD

**Issue by mgeisler** [dprint/dprint#726]
Version: 0.40.0

Today, I noticed my [GitHub Action failed](https://github.com/google/comprehensive-rust/actions/runs/5708687281/job/15483185826) with

```
Compiling https://plugins.dprint.dev/markdown-0.15.2.wasm
Compiling https://plugins.dprint.dev/toml-0.5.4.wasm
Compiling https://plugins.dprint.dev/json-0.17.2.wasm
[dprint-plugin-exec]
Error: Error reading message from stdin.

Caused by:
    failed to fill whole buffer
Error: Error reading message from stdin.

Caused by:
    failed to fill whole buffer
Error resolving plugin https://plugins.dprint.dev/exec-0.3.5.json: Failed plugin schema verification. This may indicate you are using an old version of the dprint CLI or plugin and should upgrade.: The plugin schema version was 4, but expected 5.
Error: Process completed with exit code 12
```

Based on the "The plugin schema version was 4, but expected 5", I figured I could fix this by updating the version of the plugin in the config file.

However, `dprint config update` fails with the same error when I run it locally (with `dprint` version 0.40.0).

I guess I have two questions:

- How can I update the plugin by hand?
- Can `dprint` learn to not error out on the existing config?

Thanks for any help!

**Comment by dsherret** [comment]
Yeah, sorry. It was too much work for me to maintain backwards compatibility when breaking the process plugin interface.

You will either need to upgrade the plugins (https://github.com/dprint/dprint/releases/tag/0.40.0) or pin the version on the CI to 0.39.1:

```
- uses: dprint/check@v2.2
  with:
    dprint-version: 0.39.1
```

Here's your upgraded config file:

```json
{
  "lineWidth": 80,
  "json": {},
  "markdown": {
    "textWrap": "always"
  },
  "exec": {
    "commands": [{
      "command": "rustfmt --edition 2021",
      "ext": "rs"
    }]
  },
  "excludes": [
    "/book/",
    "/src/",
    "/third_party/",
    "target/"
  ],
  "plugins": [
    "https://plugins.dprint.dev/exec-0.4.2.json@ca3c3d1cc1105b4ac1c31afdb26791a90209f13a5950f8de00dcab5e5ee293a7",
    "https://plugins.dprint.dev/json-0.17.2.wasm",
    "https://plugins.dprint.dev/markdown-0.15.2.wasm",
    "https://plugins.dprint.dev/toml-0.5.4.wasm"
  ]
}
```

**Comment by dsherret** [comment]
I'm sorry that at least the error message was not good. I should have thought about that more and have since improved this in #732. I'm doing a patch release now.

**Comment by awixor** [comment]
You might need to delete `node_modules` and run `pnpm i`  to fix this
