### ISSUE TITLE
Add `dprint lsp` command

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#738]
Use https://crates.io/crates/tower-lsp -- It would be good to have this for support with more editors. Keep around the editor-service for now to evaluate the differences and then slowly migrate. I believe using the lsp will be faster, but have higher memory usage due to needing to keep the open files in dprint's memory.

Additional notes:

* Getting the text changes based on the input and output could be copied from here: https://github.com/denoland/deno/blob/b9f407aef73dd5773638a4ce1690737209318be8/cli/lsp/text.rs#L209
* Maybe [`MaskFutureAsSend`](https://github.com/dprint/dprint/blob/b56659b7c6a1095e58e61b0645d52723603f319b/crates/core/src/async_runtime.rs#L93) would be useful for just using refcell's everywhere, since tower-lsp requires Send + Sync, but dprint uses a single threaded runtime

**Comment by mskelton** [comment]
I'd love to see this to have a faster dprint integration in Neovim.

**Comment by MariaSolOs** [comment]
@dsherret do you think that such LSP extension should remain part of `dprint` "core" (i.e. this repo) or have it live somewhere else?

**Comment by dsherret** [comment]
It could be a subcommand, so live around here: https://github.com/dprint/dprint/tree/main/crates/dprint/src/commands/editor

**Comment by jakebailey** [comment]
Very excited for this, solely for the diff-based edits; TS `checker.ts` is huge and when format happens, VS Code appears to throw away all info it has like the positioning of semantic tokens and such, even though doing the same changes by hand does not.

**Comment by dsherret** [comment]
This is released in the latest dprint as the `dprint lsp` command. You can try it out in vscode by setting `"dprint.experimentalLsp": true`. I've been using it the past week and it seems to work well, but I'd like to try it out more before making it the default. At the moment, it's syncing the entire file from the client to the server instead of incrementally updating it (though the code is there to handle incremental updates). I'm not sure it's worth it to do incremental updates because of the increased risk of bugs, but I would change it to incremental if someone find it slow in their scenario.

Also, if someone knows how to set this up with Neovim and would be willing to contribute instructions, that would be very helpful (https://github.com/dprint/dprint/issues/810).

**Comment by jakebailey** [comment]
I haven't yet tested this on the TypeScript repo, but I suspect that incremental mode will have a positive impact on `checker.ts` given it's nearing 3MB. (I'm back tomorrow and it's on my list!)

**Comment by dsherret** [comment]
Yeah, that file is mostly what I was wondering about. Thanks, Jake! 😄

(FWIW, for me everything feels snappy in there and the experience of format on save is much better, but that might not be the case on a slower computer. I'll try it out on my old laptop later)

**Comment by andrewbranch** [comment]
I use vscode-neovim, and I think this may fix an issue where format-on-save with dprint crashes that extension. Looking forward to trying it next week when I'm back at my home computer.

**Comment by jakebailey** [comment]
I've had a chance to test this on `checker.ts`; I try to do some hand timing and it seems like it's slightly faster, but I think I'd need some form of automation to attempt to check before and after (and I honestly don't quite know how I'd do that).

**Comment by alihammad-gist** [comment]
It seems `dprint lsp` doesn't format using commands provided in exec section. `dprint fmt` works for exec commands though. I use the following global configuration, which i reference when starting an lsp or using fmt using `--config path` argument. I am using neovim and I make sure that an lsp client is attached to current buffer, which is connected to dprint lsp, filetypes like markdown and json etc are formatted by dprint but perl files aren't which are mentioned in commands `exts` field, as seen below.

```json
{
  "typescript": {
  },
  "json": {
  },
  "markdown": {
    "lineWidth": 67,
    "textWrap": "always"
  },
  "toml": {
  },
  "dockerfile": {
  },
  "exec": {
    "commands": [
      {
        "command": "perltidy -l 67 -i 2",
        "exts": ["pl", "pm"]
      }
    ]
  },
  "excludes": [
    "**/node_modules",
    "**/*-lock.json"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.88.10.wasm",
    "https://plugins.dprint.dev/json-0.19.1.wasm",
    "https://plugins.dprint.dev/markdown-0.16.3.wasm",
    "https://plugins.dprint.dev/toml-0.6.0.wasm",
    "https://plugins.dprint.dev/dockerfile-0.3.0.wasm",
    "https://plugins.dprint.dev/prettier-0.35.0.json@0df49c4d878bb1051af2fa1d1f69ba6400f4b78633f49baa1f38954a6fd32b40",
    "https://plugins.dprint.dev/exec-0.4.4.json@c207bf9b9a4ee1f0ecb75c594f774924baf62e8e53a2ce9d873816a408cecbf7"
  ]
}
```
