### ISSUE TITLE
Future plugin system improvements

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#798]
- Send log level on initialize so plugins can output with verbose logging.
- Send past version with upgrade message (if not already done)
- Logging with log level in wasm plugins
- Ability for plugins to tell if no_color and if a tty. Probably send on init
- Maybe ability for Wasm plugin to import another wasm plugin via Wasm imports?
- Wasm schema should not require instantiating a wasm module (it should be figured out by just analyzing the import names)
- Ability for plugins to do comparisons with language aware algorithms (ex. for sorting imports).

**Comment by Phault** [comment]
I'm curious what your thoughts are on [Extism](https://extism.org)? Would you ever consider switching out your current Wasm-plugin system, for something built on top of that instead?

As you mention yourself in the docs, there's a lot of low-level plumbing code to write, if you're not using the `dprint-core` crate. Being able to use the Extism Plug-in Development Kits would both reduce the amount of code needed, as well as not requiring low-level skills, thus significantly lowering the bar for creating new plugins.

Anecdotally I code in C# daily, but never actually touched interop code in it, so I was at a complete loss when trying to skaffold a new Wasm plugin in it. Admittedly I quickly gave up. 

That said, I've had little exposure to Extism from the host side of things, and I've no idea how lightweight both sides are. There's also always the risk of abandonment, but it seems to have a thriving community behind it.

**Comment by dsherret** [comment]
Duplicate of https://github.com/dprint/dprint/issues/532

@Phault that looks quiet nice. That said, I'd rather have full control over the interface to tailor it for dprint and also not be locked into another project (also, it's not MIT/Apache). Additionally, I don't want to allow the Wasm plugins to have access to the file system, but it looks like that uses WASI.

> Anecdotally I code in C# daily, but never actually touched interop code in it, so I was at a complete loss when trying to skaffold a new Wasm plugin in it. Admittedly I quickly gave up.

C# has not been in a good state for this until recently. I believe it's now possible using NativeAOT-LLVM to compile to a single .wasm file without needing extra instrumentation: https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM -- I'm going to investigate switching [dprint-plugin-roslyn](https://github.com/dprint/dprint-plugin-roslyn) over to that in the future.

**Comment by Phault** [comment]
> @Phault that looks quiet nice. That said, I'd rather have full control over the interface to tailor it for dprint and also not be locked into another project (also, it's not MIT/Apache). Additionally, I don't want to allow the Wasm plugins to have access to the file system, but it looks like that uses WASI.

@dsherret Thanks for entertaining the idea and I totally get your reasoning. I believe the WASI part is optional but of course that doesn't help on the other fronts.

> C# has not been in a good state for this until recently. I believe it's now possible using NativeAOT-LLVM to compile to a single .wasm file without needing extra instrumentation: https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM -- I'm going to investigate switching [dprint-plugin-roslyn](https://github.com/dprint/dprint-plugin-roslyn) over to that in the future.

Interesting, I'll keep an eye on the roslyn plugin repo then. :)
