### ISSUE TITLE
Can't remove BOM

### ISSUE THREAD

**Issue by foriequal0** [dprint/dprint#811]
Version: 0.45.0

https://github.com/dprint/dprint/blob/5813e59f3d4804f794aa3acbac1e9e41467d1ff7/crates/dprint/src/commands/formatting.rs#L249

I stumbled upon this while trying to make a wasm plugin that removes BOM.

Related PR: https://github.com/dprint/dprint/pull/792

**Comment by dsherret** [comment]
Yeah, this should be removed from the CLI. It shouldn't be a concern for dprint, but rather the plugins.
