### ISSUE TITLE
CI GH Actions compile error

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint#812]
Version: 0.45.0

GH Action build: https://github.com/dalisoft/airlight/actions/runs/7407462678/job/20153731192#step:8:18

Config file: https://github.com/dalisoft/airlight/blob/master/dprint.json

**Comment by dsherret** [comment]
Are you sure that's dprint failing? It would output an error message if it exited with a 1 exit code. What is smartlint and how is dprint run here?

**Comment by dalisoft** [comment]
Thank you for reply @dsherret 

- Yes, i am sure it's `dprint` failing
- I don't know why it's does not showing error message, maybe because of error in step of compiling?
- **smartlint** is linter command executor which rans in order of specified by user (or by defaults) so user get results from multiple linters for different kind of files
- **dprint** is part of updated **smartlint** for faster running

**Comment by dsherret** [comment]
Also, maybe try with `dprint check --verbose` to see everything it's doing.
