### ISSUE TITLE
JSON config schema file

### ISSUE THREAD

**Issue by o-az** [dprint/dprint#817]
The only one I was able to find is this: https://dprint.dev/schemas/v0.json

Is this the most up to date?

Thank you

**Comment by dsherret** [comment]
Yes, it should be up to date. That's the schema for the CLI options in the config. For the plugin schemas, they distribute it themselves as a "config schema URL". For example, dprint-plugin-typescript distributes its schema at https://plugins.dprint.dev/dprint/dprint-plugin-typescript/0.88.10/schema.json which is a redirect to the schema.json file in the plugin's github release https://github.com/dprint/dprint-plugin-typescript/releases/tag/0.88.10 -- then the dprint vscode extension creates a final JSON schema based on the plugins and the versions you specified.
