### ISSUE TITLE
plugin-prettier causes `dprint fmt` to crash on Apple M3

### ISSUE THREAD

**Issue by eps1lon** [dprint/dprint#834]
Version: 0.45.0

Using `prettier-0.36.0.json@5cc11bcb86b783ba9e33d171ee5caefe413a6ee31a4f1521592ccb28363412af` in this config: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/06562d6790835af1d6bb77aaf957dec81389370a/.dprint.jsonc#L56

```bash
$ dprint fmt types/react-redux-toastr/react-redux-toastr-tests.ts
Error resolving plugin https://plugins.dprint.dev/prettier-0.36.0.json: Error starting ~/Library/Caches/dprint/cache/plugins/dprint-plugin-prettier/0.36.0/aarch64/dprint-plugin-prettier with args [--parent-pid 22797 --init]. Bad CPU type in executable (os error 86)
```

Every invocation of `dprint fmt` downloads the prettier plugin again. Once I remove the plugin, `dprint fmt *.tsx` works again

**Comment by dsherret** [comment]
Should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69177/files since there's a new build of the prettier plugin that has an aarch64 build.

Or intalling rosetta will also fix it with the old version

**Comment by eps1lon** [comment]
Nice, thanks for quick update!
