### ISSUE TITLE
On some Windows machines: "Connection Failed: tls connection init failed: invalid peer certificate: UnknownIssuer"

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint#849]
Version: 0.45.1

Not clear if this is #591 reopened, but @sheetalkamat is experiencing an issue with dprint where it fails to download the plugins:

```
Error resolving plugin https://plugins.dprint.dev/typescript-0.90.5.wasm: Error downloading https://plugins.dprint.dev/typescript-0.90.5.wasm - Error: https://plugins.dprint.dev/typescript-0.90.5.wasm: Connection Failed: tls connection init failed: invalid peer certificate: UnknownIssuer
```

Loading https://plugins.dprint.dev worked, as did fetching the page from `node` in the same terminal, but `npx dprint check` itself fails.

Not really sure what it would be, if dprint is already using the system certs and other apps work fine.

**Comment by dsherret** [comment]
Closed by #850
