### ISSUE TITLE
How to use exec with multiple commands

### ISSUE THREAD

**Issue by opensourcecheemsburgers** [dprint/dprint#863]
The following command works from the fish shell:

```
cat 'website/src/components/device_mockups.rs' | leptosfmt --stdin --rustfmt | rustywind --stdin
```

However, when used in a dprint exec command, it only does the `leptosfmt` command and not the `rustywind` command.

```
  "exec": {
    "commands": [{
      "command": "cat {{file_path}} | leptosfmt --stdin --rustfmt | rustywind --stdin",
      "exts": ["rs"]
    }]
  }
```

Reordering the commands still results in only `leptosfmt` working.

Here's the repo for reference: https://github.com/opensourcecheemsburgers/portfolio-website

**Comment by dsherret** [comment]
Maybe:

```
  "exec": {
    "commands": [{
      "command": "fish -c 'leptosfmt --stdin --rustfmt | rustywind --stdin'",
      "exts": ["rs"]
    }]
  }
```

**Comment by opensourcecheemsburgers** [comment]
That does not work either unfortuately. I have also tried using [`pee`](https://linux.die.net/man/1/pee) (lol) and it does not work.

However, it seems that [`Leptosfmt`](https://github.com/bram209/leptosfmt) has added [built-in support](https://github.com/bram209/leptosfmt/issues/116) for [`Rustywind`](https://github.com/avencera/rustywind).

Thanks for the help and dprint :) I might create a `dprint-leptosfmt-plugin` if it is not too difficult.
