### ISSUE TITLE
Add pretty_yaml, malva, markup_fmt to playground and `dprint init`

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#883]
We'll need to update this file first:

https://github.com/dprint/plugins/blob/main/info.json

Then update the website/playground folder.

FYI @g-plane in case you're interested in taking this one on.

**Comment by g-plane** [comment]
PR: https://github.com/dprint/plugins/pull/19

**Comment by dsherret** [comment]
Thanks! It's working:

![image](https://github.com/dprint/dprint/assets/1609021/8596fdfa-5d79-4e9f-a7dd-288691ea1fbd)

**Comment by g-plane** [comment]
I'll open PR for updating playground later.
