### ISSUE TITLE
[Meta] Logo Suggestions

### ISSUE THREAD

**Issue by g-plane** [dprint/dprint#893]
I made logos with different colors and let you choose. In all the logos below, the left part stands for "d" and the right part stands for "p".

### No Shadow

32x32:
![a-no_shadow_图层 1_-32x32](https://github.com/user-attachments/assets/75dd9b84-a9dd-45cc-b590-165fdcba1d95)
64x64:
![a-no_shadow_图层 1_-64x64](https://github.com/user-attachments/assets/790c3ba9-3707-4311-b848-66d156605f81)
256x256:
![a-no_shadow_图层 1_-256x256](https://github.com/user-attachments/assets/51877f8c-4e9c-4ff1-b928-36ac3b8abdaa)
512x512:
![a-no_shadow_图层 1_-512x512](https://github.com/user-attachments/assets/50d556fb-5af4-40d5-925b-03d5b1042cd5)

### Shadowed

32x32:
![a-shadowed_图层 1_-32x32](https://github.com/user-attachments/assets/1e8010d7-86db-47f9-9d5b-b362a23af86e)
64x64:
![a-shadowed_图层 1_-64x64](https://github.com/user-attachments/assets/3a9089bc-eded-4688-b72e-7e3d6e7031d5)
256x256:
![a-shadowed_图层 1_-256x256](https://github.com/user-attachments/assets/a02492e1-6c91-4ea0-8d45-d325914c616e)
512x512:
![a-shadowed_图层 1_-512x512](https://github.com/user-attachments/assets/47b9e3b9-e94d-4667-89ed-783ab847a4b7)

### No Shadow

32x32:
![b-no_shadow_图层 1_-32x32](https://github.com/user-attachments/assets/76edfcab-c8c4-415b-b41c-f954cbf7e2b3)
64x64:
![b-no_shadow_图层 1_-64x64](https://github.com/user-attachments/assets/a2ed90a9-993d-41d9-8baf-05afb47d1303)
256x256:
![b-no_shadow_图层 1_-256x256](https://github.com/user-attachments/assets/7eea1dcb-2132-4dae-b84e-41e1d6cb437d)
512x512:
![b-no_shadow_图层 1_-512x512](https://github.com/user-attachments/assets/9545be98-100f-490d-af55-fc424f125249)

### Shadowed

32x32:
![b-shadowed_图层 1_-32x32](https://github.com/user-attachments/assets/0e208756-c655-46aa-8e8f-ff6d280c185a)
64x64:
![b-shadowed_图层 1_-64x64](https://github.com/user-attachments/assets/cd3d5b5b-f8ea-4b18-bf1d-b202d8cb003c)
256x256:
![b-shadowed_图层 1_-256x256](https://github.com/user-attachments/assets/8c865bb8-aa99-4e42-9909-669c83faacb6)
512x512:
![b-shadowed_图层 1_-512x512](https://github.com/user-attachments/assets/887684a7-0730-4c8b-98ce-278f14a91ffd)

### No Shadow

32x32:
![c-no_shadow_图层 1_-32x32](https://github.com/user-attachments/assets/cf4f7403-29e3-4f32-95ab-20914bacdec4)
64x64:
![c-no_shadow_图层 1_-64x64](https://github.com/user-attachments/assets/eb637930-8a6a-49fb-b56c-a79ef0a4eedb)
256x256:
![c-no_shadow_图层 1_-256x256](https://github.com/user-attachments/assets/dcf8dd76-0eca-4522-a61e-ae37e6cd1537)
512x512:
![c-no_shadow_图层 1_-512x512](https://github.com/user-attachments/assets/597cf5ad-cff1-4aab-8bfb-ace33d6c09cf)

### Shadowed

32x32:
![c-shadowed_图层 1_-32x32](https://github.com/user-attachments/assets/a4d0fdb7-bd67-426e-8f18-a999b4fc2bfd)
64x64:
![c-shadowed_图层 1_-64x64](https://github.com/user-attachments/assets/0a6f9193-4a85-4cfd-8c17-685e6ccc3c36)
256x256:
![c-shadowed_图层 1_-256x256](https://github.com/user-attachments/assets/290ac75b-2e3e-4090-91bb-e1af25146bbf)
512x512:
![c-shadowed_图层 1_-512x512](https://github.com/user-attachments/assets/56c8c69a-3815-4b07-84c5-74aca33e3f0f)

### No Shadow

32x32:
![d-no_shadow_图层 1_-32x32](https://github.com/user-attachments/assets/d22b42c5-423f-4af5-9d70-276675c47124)
64x64:
![d-no_shadow_图层 1_-64x64](https://github.com/user-attachments/assets/49ed20a8-623a-4df3-afa6-816623e5f9bf)
256x256:
![d-no_shadow_图层 1_-256x256](https://github.com/user-attachments/assets/8530ef43-d584-4410-a6de-3c263fc62c35)
512x512:
![d-no_shadow_图层 1_-512x512](https://github.com/user-attachments/assets/24461da2-1bef-4157-9d7a-439f3c054f67)

### Shadowed

32x32:
![d-shadowed_图层 1_-32x32](https://github.com/user-attachments/assets/5a9930d9-9149-4368-9989-4e69d25a829a)
64x64:
![d-shadowed_图层 1_-64x64](https://github.com/user-attachments/assets/29a18b9b-0738-42a9-9108-8343b73a19a7)
256x256:
![d-shadowed_图层 1_-256x256](https://github.com/user-attachments/assets/00c4cc87-e050-4d7c-a4ee-0ef44f4d695b)
512x512:
![d-shadowed_图层 1_-512x512](https://github.com/user-attachments/assets/0e241fdd-13ad-4a2e-b7cd-20c0f7978007)

### No Shadow

32x32:
![e-no_shadow_图层 1_-32x32](https://github.com/user-attachments/assets/f7d21e81-fc6b-4277-a534-5a56eece3114)
64x64:
![e-no_shadow_图层 1_-64x64](https://github.com/user-attachments/assets/703fb526-0214-4c9c-b73a-e9f53aed1b33)
256x256:
![e-no_shadow_图层 1_-256x256](https://github.com/user-attachments/assets/011e824d-257e-4caf-bfa6-d99e4675d78d)
512x512:
![e-no_shadow_图层 1_-512x512](https://github.com/user-attachments/assets/7a4e476e-5758-4fd2-9521-ed1f3fe9d9be)

### Shadowed

32x32:
![e-shadowed_图层 1_-32x32](https://github.com/user-attachments/assets/2abbeca8-ae43-4492-9bdf-d3779cf97598)
64x64:
![e-shadowed_图层 1_-64x64](https://github.com/user-attachments/assets/6e600e09-ca0d-4e02-8ef5-6a081b689e57)
256x256:
![e-shadowed_图层 1_-256x256](https://github.com/user-attachments/assets/bebb1e1d-5230-462f-95b0-3a86a5bb726b)
512x512:
![e-shadowed_图层 1_-512x512](https://github.com/user-attachments/assets/a9c3cd0a-7fca-4a62-b084-7008bf09a222)

---

Any ideas?

**Comment by dsherret** [comment]
Thanks @g-plane. I appreciate your effort, but I'm not too big on it. Sorry!
