### ISSUE TITLE
Running `npm install` with no package-lock.json does not install all dprint dependencies

### ISSUE THREAD

**Issue by todor-a** [dprint/dprint#896]
Version: 0.47.0.

Whenever I try to do a "clean install" (no package-lock.json), not all dprint peer-dependencies are installed. The issue is fixed when I delete node_modules as well.

The error is:
```
Cannot find module '@dprint/linux-x64-musl/package.json'
```

System info:
```
┌─────────────────────────────────────────────────────────────────────────────────────────┐
│  SYSTEMINFORMATION                                                     Version: 5.22.11 │
└─────────────────────────────────────────────────────────────────────────────────────────┘

Operating System:
──────────────────────────────────────────────────────────────────────────────────────────
Platform         : darwin
Distro           : macOS
Release          : 14.4.1
Codename         : macOS Sonoma
Kernel           : 23.4.0
Arch             : arm64
Codepage         : UTF-8
Build            : 23E224

System:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Apple Inc.
Model            : MacBookPro
Version          : 18,1
Virtual          :

CPU:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Apple
Brand            : M1 Pro
Family           : 458787763
Model            :
Stepping         : 4
Speed            : 2.4
Cores            : 10
PhysicalCores    : 10
PerformanceCores : 8
EfficiencyCores  : 2
Processors       : 1
Socket           : SOC
```

**Comment by dsherret** [comment]
That makes no sense to me. dprint defines `@dprint/linux-x64-musl` as an optional dependency and `@dprint/linux-x64-musl` is defined in its package.json as only being for "linux", "x64", and "musl". Do you have a reproduction I can try? What tools is creating that "Cannot find module '@dprint/linux-x64-musl/package.json'" error?

**Comment by todor-a** [comment]
Not sure how valuable it is but yes - https://github.com/todor-a/dprint-install-repro. I manage to reproduce it every time. This  causes issues on CI, which uses linux.

**Comment by dsherret** [comment]
I'm not able to reproduce on Mac. What version of npm are you using? I have 10.8.2

**Comment by todor-a** [comment]
Was on `10.7.0`. Upgraded to latest (`10.8.2`) and can't reproduce as well...

**Comment by dsherret** [comment]
It sounds like an npm bug because I don't see anything wrong with dprint's npm packages. Maybe they fixed it.

**Comment by todor-a** [comment]
Yep. Sorry and thanks.

**Comment by dsherret** [comment]
No need to apologize! This information is good to have documented in an issue as it may help someone in the future.

**Comment by todor-a** [comment]
p.s. I think this is the [issue](https://github.com/npm/cli/issues/4828) that causes problems.
