### ISSUE TITLE
Official HTML & CSS Plugin

### ISSUE THREAD

**Issue by trymeouteh** [dprint/dprint#936]
To have an official plugin for HTML and CSS formatting.

**Comment by UnknownPlatypus** [comment]
There are plugins for both HTML and CSS listed in the readme

**Comment by UnknownPlatypus** [comment]
They are indeed not "official" but trusted third party to the point they were added to dprint readme.

PS: Both are used under the hood in `deno fmt` too if you are looking for reason to trust them

**Comment by dsherret** [comment]
> My main concern is long term support and reconization.

Malva and markup_fmt are both used in Deno now. I recommend using them.
