### ISSUE TITLE
Request: switch from `ureq` to `curl`

### ISSUE THREAD

**Issue by bradzacher** [dprint/dprint#950]
<details>
<summary>Context / Backstory</summary>

We've been working on making some internal changes to our dprint setup at Canva.

Previously we used to rely on [nix](https://nixos.org/) to manage our binary dependencies. We had some custom infra that used nix to fetch all of the plugin files and then we had a wrapper script for dprint that would inject the plugin disk paths via the `--plugins` flag.

It's a complicated setup and a pain to think about and manage -- but it works and it means we have things cached in our internal caches.

We're working on trying to shed complexity here by removing nix from the equation. This means we'll rely on dprint doing fetches from the web instead of just reading from disk.

The complex bit we've run into is that we have complexities in our infra that we can't currently remove that requires external URLs (such as GH) to use a proxy and internal URLs (eg the internal cache) to not use a proxy. We leverage the `HTTPS_PROXY` and `NO_PROXY` environment variables to define this and tools like `curl` respect both of these env vars and thus work just fine.

---

</details>

`ureq` doesn't support all the features that one would want to do fetching in complex corporate environments. For example it does not support `NO_PROXY` which makes it impossible to use dprint with a split setup where some URLs must go via a proxy and some must not.

It looks like `ureq` might be planning on supporting `NO_PROXY` in their next major (https://github.com/algesten/ureq/issues/668), but the question is -- could we avoid this entirely and instead use a solution that already supports this and provides more features?
The [`curl` crate](https://crates.io/crates/curl) is used by tools like `cargo` and it allows you to leverage `libcurl` to do your fetching -- meaning you get the same power and flexibility as the `curl` binary.

What do we think about migrating from `ureq` to `curl`?

**Comment by dsherret** [comment]
I'm somewhat uneasy about switching because there's lots of bugs related to things like certificates that I've managed to fix with the current setup (ex. some certificates are embedded within dprint itself). I'm not sure if those would pop up again with libcurl. Is NO_PROXY the only thing? I don't think it's too complicated to implement (the implementation could probably be lifted from Deno).

**Comment by bradzacher** [comment]
`NO_PROXY` is the thing we need right now, yeah so that we can have dprint do both proxied and unproxied requests. That may be enough in of itself to get us over the line for now.

Though part of me does wonder if the cert issues would work fine via libcurl where it might be able to better source them from the system? Regardless that's well and truly outside my expertise - I fully defer to you on that front!

If you think that implementing`NO_PROXY` in dprint is viable then I am happy to go with that approach. Libcurl was just a suggestion cos it would be built-in already!

**Comment by dsherret** [comment]
Should be working now in 0.48. Let me know if you run into any issues (I didn't do an integration test and only unit tests).
